id = "surrealql"
name = "SurrealQL"
description = "SurrealQL language support — syntax highlighting, completions, diagnostics, hover, formatting"
version = "0.1.1"
schema_version = 1
authors = ["overrealdb"]
repository = "https://github.com/overrealdb/surql-parser"

[grammars.surrealql]
repository = "https://github.com/overrealdb/tree-sitter-surrealql"
rev = "191cc5e250bedf6106c34f65be3e238a0a6f97cb"

[language_servers.surql-lsp]
name = "surql-lsp"
languages = ["SurrealQL", "Rust"]
