#![cfg(feature = "build")]

use std::path::Path;

fn create_temp_schema(dir: &Path, filename: &str, content: &str) {
	std::fs::create_dir_all(dir).unwrap();
	std::fs::write(dir.join(filename), content).unwrap();
}

#[test]
fn validate_schema_valid_files() {
	let dir = tempfile::tempdir().unwrap();
	create_temp_schema(
		dir.path(),
		"schema.surql",
		"DEFINE TABLE user SCHEMAFULL;\nDEFINE FIELD name ON user TYPE string;\n",
	);
	create_temp_schema(
		dir.path(),
		"functions.surql",
		"DEFINE FUNCTION fn::greet($name: string) { RETURN 'Hello, ' + $name; };\n",
	);

	// Should not panic
	surql_parser::build::validate_schema(dir.path());
}

#[test]
#[should_panic(expected = "SurrealQL validation failed")]
fn validate_schema_invalid_file() {
	let dir = tempfile::tempdir().unwrap();
	create_temp_schema(dir.path(), "bad.surql", "SELEC * FORM user;");

	surql_parser::build::validate_schema(dir.path());
}

#[test]
fn validate_schema_empty_dir() {
	let dir = tempfile::tempdir().unwrap();
	// Should not panic — no .surql files
	surql_parser::build::validate_schema(dir.path());
}

#[test]
fn generate_typed_functions_produces_constants() {
	let schema_dir = tempfile::tempdir().unwrap();
	create_temp_schema(
		schema_dir.path(),
		"functions.surql",
		"\
DEFINE FUNCTION fn::greet($name: string) { RETURN 'Hello, ' + $name; };
DEFINE FUNCTION fn::add($a: int, $b: int) -> int { RETURN $a + $b; };
",
	);

	let out_dir = tempfile::tempdir().unwrap();
	let out_file = out_dir.path().join("surql_functions.rs");

	surql_parser::build::generate_typed_functions(schema_dir.path(), &out_file);

	let generated = std::fs::read_to_string(&out_file).unwrap();

	// Check header
	assert!(generated.contains("Auto-generated by surql-parser"));

	// Check constants exist
	assert!(generated.contains("FN_GREET"));
	assert!(generated.contains("\"fn::greet\""));
	assert!(generated.contains("FN_ADD"));
	assert!(generated.contains("\"fn::add\""));

	// Check parameter docs
	assert!(generated.contains("$name: string"));
	assert!(generated.contains("$a: int, $b: int"));

	// Check return type doc
	assert!(generated.contains("Returns: `int`"));
}

#[test]
fn generate_typed_functions_empty_schema() {
	let schema_dir = tempfile::tempdir().unwrap();
	create_temp_schema(
		schema_dir.path(),
		"tables.surql",
		"DEFINE TABLE user SCHEMAFULL;\n",
	);

	let out_dir = tempfile::tempdir().unwrap();
	let out_file = out_dir.path().join("surql_functions.rs");

	surql_parser::build::generate_typed_functions(schema_dir.path(), &out_file);

	let generated = std::fs::read_to_string(&out_file).unwrap();
	// Should have header but no constants
	assert!(generated.contains("Auto-generated"));
	assert!(!generated.contains("pub const"));
}

#[test]
fn generate_typed_functions_nested_name() {
	let schema_dir = tempfile::tempdir().unwrap();
	create_temp_schema(
		schema_dir.path(),
		"functions.surql",
		"DEFINE FUNCTION fn::user::get($id: int) { RETURN $id; };\n",
	);

	let out_dir = tempfile::tempdir().unwrap();
	let out_file = out_dir.path().join("surql_functions.rs");

	surql_parser::build::generate_typed_functions(schema_dir.path(), &out_file);

	let generated = std::fs::read_to_string(&out_file).unwrap();
	assert!(generated.contains("FN_USER_GET"));
	assert!(generated.contains("\"fn::user::get\""));
}

// ─── Additional build helper tests ───

#[test]
fn validate_schema_skips_non_surql_files() {
	let dir = tempfile::tempdir().unwrap();
	// Valid .surql file
	create_temp_schema(dir.path(), "good.surql", "SELECT * FROM user;\n");
	// Non-.surql files with invalid content — should be ignored
	create_temp_schema(dir.path(), "notes.txt", "this is not sql at all!!!");
	create_temp_schema(dir.path(), "data.json", "{\"invalid\": \"sql\"}");
	create_temp_schema(dir.path(), "script.sh", "echo hello");

	// Should not panic — only .surql files are validated
	surql_parser::build::validate_schema(dir.path());
}

#[test]
fn validate_schema_nested_directories() {
	let dir = tempfile::tempdir().unwrap();
	let subdir = dir.path().join("migrations").join("v1");
	create_temp_schema(
		&subdir,
		"001_users.surql",
		"DEFINE TABLE user SCHEMAFULL;\n",
	);
	create_temp_schema(
		&subdir,
		"002_fields.surql",
		"DEFINE FIELD name ON user TYPE string;\n",
	);

	let subdir2 = dir.path().join("migrations").join("v2");
	create_temp_schema(
		&subdir2,
		"001_posts.surql",
		"DEFINE TABLE post SCHEMAFULL;\n",
	);

	surql_parser::build::validate_schema(dir.path());
}

#[test]
#[should_panic(expected = "SurrealQL validation failed")]
fn validate_schema_nested_invalid() {
	let dir = tempfile::tempdir().unwrap();
	let subdir = dir.path().join("deep").join("nested");
	create_temp_schema(subdir.as_path(), "bad.surql", "INVALID SYNTAX HERE");

	surql_parser::build::validate_schema(dir.path());
}

#[test]
#[should_panic(expected = "2 error")]
fn validate_schema_reports_all_errors() {
	let dir = tempfile::tempdir().unwrap();
	create_temp_schema(dir.path(), "a_bad.surql", "SELEC * FROM user");
	create_temp_schema(dir.path(), "b_also_bad.surql", "CREAT user SET x = 1");
	create_temp_schema(
		dir.path(),
		"c_good.surql",
		"SELECT * FROM user;\n", // this one is fine
	);

	surql_parser::build::validate_schema(dir.path());
}

#[test]
fn generate_typed_functions_from_multiple_files() {
	let schema_dir = tempfile::tempdir().unwrap();
	create_temp_schema(
		schema_dir.path(),
		"a_users.surql",
		"DEFINE FUNCTION fn::user::create($name: string) { RETURN CREATE user SET name = $name; };\n",
	);
	create_temp_schema(
		schema_dir.path(),
		"b_posts.surql",
		"DEFINE FUNCTION fn::post::list() -> array { RETURN SELECT * FROM post; };\n",
	);

	let out_dir = tempfile::tempdir().unwrap();
	let out_file = out_dir.path().join("surql_functions.rs");

	surql_parser::build::generate_typed_functions(schema_dir.path(), &out_file);

	let generated = std::fs::read_to_string(&out_file).unwrap();
	// Functions from both files should be present
	assert!(generated.contains("FN_USER_CREATE"));
	assert!(generated.contains("\"fn::user::create\""));
	assert!(generated.contains("FN_POST_LIST"));
	assert!(generated.contains("\"fn::post::list\""));
}

#[test]
fn generate_typed_functions_no_params_no_return() {
	let schema_dir = tempfile::tempdir().unwrap();
	create_temp_schema(
		schema_dir.path(),
		"functions.surql",
		"DEFINE FUNCTION fn::ping() { RETURN 'pong'; };\n",
	);

	let out_dir = tempfile::tempdir().unwrap();
	let out_file = out_dir.path().join("surql_functions.rs");

	surql_parser::build::generate_typed_functions(schema_dir.path(), &out_file);

	let generated = std::fs::read_to_string(&out_file).unwrap();
	assert!(generated.contains("FN_PING"));
	assert!(generated.contains("\"fn::ping\""));
	// No "Parameters:" line since no params
	assert!(!generated.contains("Parameters:"));
	// No "Returns:" line since no return type
	assert!(!generated.contains("Returns:"));
}

#[test]
fn generate_typed_functions_complex_types() {
	let schema_dir = tempfile::tempdir().unwrap();
	create_temp_schema(
		schema_dir.path(),
		"functions.surql",
		"\
DEFINE FUNCTION fn::find_related($record: record<user>, $depth: int) -> array {
	RETURN SELECT * FROM user;
};
",
	);

	let out_dir = tempfile::tempdir().unwrap();
	let out_file = out_dir.path().join("surql_functions.rs");

	surql_parser::build::generate_typed_functions(schema_dir.path(), &out_file);

	let generated = std::fs::read_to_string(&out_file).unwrap();
	assert!(generated.contains("FN_FIND_RELATED"));
	assert!(generated.contains("record<user>"));
	assert!(generated.contains("$depth: int"));
	assert!(generated.contains("Returns: `array`"));
}

#[test]
fn generate_typed_functions_output_is_valid_rust() {
	let schema_dir = tempfile::tempdir().unwrap();
	create_temp_schema(
		schema_dir.path(),
		"functions.surql",
		"\
DEFINE FUNCTION fn::greet($name: string) { RETURN 'Hello, ' + $name; };
DEFINE FUNCTION fn::add($a: int, $b: int) -> int { RETURN $a + $b; };
DEFINE FUNCTION fn::user::list() -> array { RETURN SELECT * FROM user; };
",
	);

	let out_dir = tempfile::tempdir().unwrap();
	let out_file = out_dir.path().join("surql_functions.rs");

	surql_parser::build::generate_typed_functions(schema_dir.path(), &out_file);

	let generated = std::fs::read_to_string(&out_file).unwrap();
	// Verify it's syntactically valid Rust by checking structure
	for line in generated.lines() {
		if line.starts_with("pub const") {
			assert!(line.contains(": &str = \"fn::"), "Bad const line: {line}");
			assert!(line.ends_with("\";"), "Const line not terminated: {line}");
		}
	}
}
