#!/usr/bin/env python3
"""Parse SurrealDB MDX docs to extract built-in function definitions.

Reads MDX files from the SurrealDB docs repo and generates a Rust source file
with all built-in function signatures, descriptions, and namespaces.

Usage: python3 parse-builtins.py <docs-dir> <output-file>
  docs-dir:    path to src/content/doc-surrealql/functions/database/
  output-file: path to write generated Rust file
"""

import os
import re
import sys
from pathlib import Path


def parse_mdx_file(path: str) -> list[dict]:
    """Extract function definitions from an MDX file."""
    with open(path) as f:
        content = f.read()

    # Remove YAML frontmatter
    if content.startswith('---'):
        end = content.find('---', 3)
        if end != -1:
            content = content[end + 3:]

    functions = []
    # Split by ## headers (not ### or deeper)
    sections = re.split(r'^## (?!#)', content, flags=re.MULTILINE)

    for section in sections[1:]:  # Skip content before first ##
        # Extract function name from header: `namespace::name`
        header_match = re.match(r'`([a-z][a-z0-9_]*(?:::[a-z][a-z0-9_]*)+)`', section)
        if not header_match:
            continue

        name = header_match.group(1)

        # Extract description: first non-empty paragraph after header
        lines = section.split('\n')
        desc_lines = []
        started = False
        for line in lines[1:]:
            stripped = line.strip()
            # Stop at sub-headers, code blocks, or component tags
            if stripped.startswith('#') or stripped.startswith('```'):
                break
            if stripped.startswith('<') or stripped.startswith(':::'):
                if started:
                    break
                continue
            if stripped:
                started = True
                desc_lines.append(stripped)
            elif started:
                break

        description = ' '.join(desc_lines).strip()
        # Clean markdown links: [text](url) → text
        description = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', description)
        # Clean inline code: `code` → code
        description = re.sub(r'`([^`]+)`', r'\1', description)
        # Escape double quotes for Rust string
        description = description.replace('\\', '\\\\').replace('"', '\\"')
        # Truncate very long descriptions
        if len(description) > 200:
            description = description[:197] + '...'

        # Extract API definition signatures
        signatures = []
        api_blocks = re.findall(
            r'```(?:surql|sql)[^\n]*(?:API DEFINITION|Api definition|API Definition)[^\n]*\n(.*?)```',
            section,
            re.DOTALL | re.IGNORECASE
        )
        for block in api_blocks:
            for sig_line in block.strip().split('\n'):
                sig_line = sig_line.strip()
                if sig_line and not sig_line.startswith('--') and not sig_line.startswith('//'):
                    sig_line = sig_line.replace('\\', '\\\\').replace('"', '\\"')
                    signatures.append(sig_line)

        if name and (description or signatures):
            functions.append({
                'name': name,
                'description': description or f"Built-in function {name}",
                'signatures': signatures,
            })

    return functions


def generate_rust(functions: list[dict], output_path: str):
    """Generate Rust source file with builtin function data."""
    functions.sort(key=lambda f: f['name'])

    # Collect unique namespaces
    namespaces = sorted(set(
        f['name'].rsplit('::', 1)[0]
        for f in functions
        if '::' in f['name']
    ))

    lines = []
    lines.append('// Auto-generated by scripts/sync-builtins.sh \u2014 do not edit manually.')
    lines.append(f'// {len(functions)} built-in functions from SurrealDB docs.')
    lines.append('//')
    lines.append('// To regenerate: cargo make sync-builtins')
    lines.append('')
    lines.append('/// A built-in SurrealQL function.')
    lines.append('#[derive(Debug, Clone)]')
    lines.append('pub struct BuiltinFn {')
    lines.append('\tpub name: &\'static str,')
    lines.append('\tpub description: &\'static str,')
    lines.append('\tpub signatures: &\'static [&\'static str],')
    lines.append('}')
    lines.append('')

    # Namespace list
    lines.append('/// All built-in function namespaces.')
    lines.append('pub static BUILTIN_NAMESPACES: &[&str] = &[')
    for ns in namespaces:
        lines.append(f'\t"{ns}",')
    lines.append('];')
    lines.append('')

    # Function list
    lines.append(f'/// All {len(functions)} built-in SurrealQL functions.')
    lines.append('pub static BUILTINS: &[BuiltinFn] = &[')

    for func in functions:
        sigs = ', '.join(f'"{s}"' for s in func['signatures'])
        lines.append(f'\tBuiltinFn {{')
        lines.append(f'\t\tname: "{func["name"]}",')
        lines.append(f'\t\tdescription: "{func["description"]}",')
        lines.append(f'\t\tsignatures: &[{sigs}],')
        lines.append(f'\t}},')

    lines.append('];')
    lines.append('')

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f'  Generated {len(functions)} functions, {len(namespaces)} namespaces')


def main():
    if len(sys.argv) != 3:
        print(f'Usage: {sys.argv[0]} <docs-dir> <output-file>', file=sys.stderr)
        sys.exit(1)

    docs_dir = Path(sys.argv[1])
    output_path = sys.argv[2]

    if not docs_dir.is_dir():
        print(f'ERROR: Directory not found: {docs_dir}', file=sys.stderr)
        sys.exit(1)

    all_functions = []
    mdx_files = sorted(docs_dir.glob('*.mdx'))

    if not mdx_files:
        print(f'ERROR: No .mdx files found in {docs_dir}', file=sys.stderr)
        sys.exit(1)

    for mdx_file in mdx_files:
        functions = parse_mdx_file(str(mdx_file))
        all_functions.extend(functions)
        if functions:
            print(f'  {mdx_file.name}: {len(functions)} functions')

    if not all_functions:
        print('ERROR: No functions extracted from docs', file=sys.stderr)
        sys.exit(1)

    generate_rust(all_functions, output_path)


if __name__ == '__main__':
    main()
