// Auto-generated by scripts/sync-builtins.sh — do not edit manually.
// 421 built-in functions from SurrealDB docs.
//
// To regenerate: cargo make sync-builtins

/// A built-in SurrealQL function.
#[derive(Debug, Clone)]
pub struct BuiltinFn {
	pub name: &'static str,
	pub description: &'static str,
	pub signatures: &'static [&'static str],
}

/// All built-in function namespaces.
pub static BUILTIN_NAMESPACES: &[&str] = &[
	"api",
	"api::req",
	"api::res",
	"array",
	"array::sort",
	"bytes",
	"crypto",
	"crypto::argon2",
	"crypto::bcrypt",
	"crypto::pbkdf2",
	"crypto::scrypt",
	"duration",
	"file",
	"geo",
	"geo::hash",
	"http",
	"math",
	"meta",
	"object",
	"parse::email",
	"parse::url",
	"rand",
	"rand::uuid",
	"record",
	"search",
	"sequence",
	"session",
	"set",
	"string",
	"string::distance",
	"string::html",
	"string::semver",
	"string::semver::inc",
	"string::semver::set",
	"string::similarity",
	"time",
	"type",
	"value",
	"vector",
	"vector::distance",
	"vector::similarity",
];

/// All 421 built-in SurrealQL functions.
pub static BUILTINS: &[BuiltinFn] = &[
	BuiltinFn {
		name: "api::invoke",
		description: "Built-in function api::invoke",
		signatures: &["api::invoke($path: string, $options: option<object>) -> object"],
	},
	BuiltinFn {
		name: "api::req::body",
		description: "Built-in function api::req::body",
		signatures: &["api::req::body($path: string, $strategy: option<string>)"],
	},
	BuiltinFn {
		name: "api::res::body",
		description: "Built-in function api::res::body",
		signatures: &["api::res::body($path: string, $strategy: option<string>)"],
	},
	BuiltinFn {
		name: "api::res::header",
		description: "The api::res::header function sets a single header for a response.",
		signatures: &["api::res::header($header_name: string, $val: value)"],
	},
	BuiltinFn {
		name: "api::res::headers",
		description: "The api::res::headers function takes an object to set the headers for a response.",
		signatures: &["api::res::headers($headers: object)"],
	},
	BuiltinFn {
		name: "api::res::status",
		description: "Built-in function api::res::status",
		signatures: &["api::res::status($http_code: int)"],
	},
	BuiltinFn {
		name: "api::timeout",
		description: "The api::timeout function sets the maximum timeout for a request.",
		signatures: &["api::timeout($timeout: duration)"],
	},
	BuiltinFn {
		name: "array::add",
		description: "The array::add function adds an item to an array only if it doesn't exist.",
		signatures: &["array::add(array, $new_val: value) -> array"],
	},
	BuiltinFn {
		name: "array::all",
		description: "When called on an array without any extra arguments, the array::all function checks whether all array values are truthy.",
		signatures: &[
			"array::all(array) -> bool",
			"array::all(array, $predicate: value) -> bool",
			"array::all(array, $predicate: closure) -> bool",
		],
	},
	BuiltinFn {
		name: "array::any",
		description: "The array::any function checks whether any array values are truthy.",
		signatures: &[
			"array::any(array) -> bool",
			"array::any(array, $predicate: value) -> bool",
			"array::any(array, $predicate: closure) -> bool",
		],
	},
	BuiltinFn {
		name: "array::append",
		description: "The array::append function appends a value to the end of an array.",
		signatures: &["array::append(array, $new_val: value) -> array"],
	},
	BuiltinFn {
		name: "array::at",
		description: "The array::at function returns the value at the specified index, or in reverse for a negative index.",
		signatures: &["array::at(array, $index: int) -> any"],
	},
	BuiltinFn {
		name: "array::boolean_and",
		description: "The array::boolean_and function performs the AND bitwise operations on the input arrays per-element based on the element's truthiness. If one array is shorter than the other it is considered null a...",
		signatures: &["array::boolean_and($lh: array, $rh: array)"],
	},
	BuiltinFn {
		name: "array::boolean_not",
		description: "The array::boolean_not function performs the NOT bitwise operations on the input array(s) per-element based on the element's truthiness. It takes in one array and it returns false if its single ope...",
		signatures: &["array::boolean_not(array)"],
	},
	BuiltinFn {
		name: "array::boolean_or",
		description: "The array::boolean_or function performs the OR bitwise operations on the input arrays per-element based on the element's truthiness. It takes two arrays and if one array is shorter than the other o...",
		signatures: &["array::boolean_or($lh: array, $rh: array)"],
	},
	BuiltinFn {
		name: "array::boolean_xor",
		description: "The array::boolean_xor function performs the XOR bitwise operations.",
		signatures: &["array::boolean_xor($lh: array, $rh: array)"],
	},
	BuiltinFn {
		name: "array::clump",
		description: "The array::clump function returns the original array split into sub-arrays of size. The last sub-array may have a length less than the length of size if size does not divide equally into the origin...",
		signatures: &["array::clump(array, $size: int) -> array"],
	},
	BuiltinFn {
		name: "array::combine",
		description: "The array::combine function combines all values from two arrays together, returning an array of arrays.",
		signatures: &["array::combine(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "array::complement",
		description: "The array::complement function returns the complement of two arrays, returning a single array containing items which are not in the second array.",
		signatures: &["array::complement(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "array::concat",
		description: "The array::concat function merges an array with one or more arrays, returning an array which may contain duplicate values. If you want to remove duplicate values from two merged arrays, then use th...",
		signatures: &["array::concat(array, $other: array, ..) -> array"],
	},
	BuiltinFn {
		name: "array::difference",
		description: "The array::difference function determines the difference between two arrays, returning a single array containing items which are not in both arrays.",
		signatures: &["array::difference(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "array::distinct",
		description: "The array::distinct function calculates the unique values in an array, returning a single array.",
		signatures: &["array::distinct(array) -> array"],
	},
	BuiltinFn {
		name: "array::fill",
		description: "The array::fill function replaces all values of an array with a new value.",
		signatures: &[
			"array::fill(array, $with: any) -> array",
			"array::fill(array, $with: any, $start: int, $end: int) -> array",
		],
	},
	BuiltinFn {
		name: "array::filter",
		description: "The array::filter function filters out values in an array that do not match a pattern, returning only the ones that do match.",
		signatures: &[
			"array::filter(array, $predicate: value) -> array",
			"array::filter(array, $predicate: closure) -> array",
		],
	},
	BuiltinFn {
		name: "array::filter_index",
		description: "The array::filter_index function returns the indexes of all occurrences of all matching values.",
		signatures: &[
			"array::filter_index(array, $predicate: value) -> array",
			"array::filter_index(array, $predicate: closure) -> array",
		],
	},
	BuiltinFn {
		name: "array::find",
		description: "The array::find function returns the first occurrence of value in the array or NONE if array does not contain value.",
		signatures: &[
			"array::find(array, $predicate: value)   -> value | NONE",
			"array::find(array, $predicate: closure) -> value | NONE",
		],
	},
	BuiltinFn {
		name: "array::find_index",
		description: "The array::find_index function returns the index of the first occurrence of value in the array or NONE if array does not contain value.",
		signatures: &[
			"array::find_index(array, $predicate: value)   -> number | NONE",
			"array::find_index(array, $predicate: closure) -> number | NONE",
		],
	},
	BuiltinFn {
		name: "array::first",
		description: "The array::first function returns the first value from an array.",
		signatures: &["array::first(array) -> any"],
	},
	BuiltinFn {
		name: "array::flatten",
		description: "The array::flatten function flattens an array of arrays, returning a new array with all sub-array elements concatenated into it.",
		signatures: &["array::flatten(array) -> array"],
	},
	BuiltinFn {
		name: "array::fold",
		description: "The array::fold function returns a final value from the elements of an array by allowing an operation to be performed at each step of the way as each subsequent item in the array is encountered. To...",
		signatures: &["array::fold(array, $initial_value: value, $operator: closure) -> value"],
	},
	BuiltinFn {
		name: "array::group",
		description: "The array::group function flattens and returns the unique items in an array.",
		signatures: &["array::group(array) -> array"],
	},
	BuiltinFn {
		name: "array::insert",
		description: "The array::insert function inserts a value into an array.",
		signatures: &[
			"array::insert(array, $insert: value) -> array",
			"array::insert(array, $insert: value, $position: int) -> array",
		],
	},
	BuiltinFn {
		name: "array::intersect",
		description: "The array::intersect function calculates the values which intersect two arrays, returning a single array containing the values which are in both arrays.",
		signatures: &["array::intersect(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "array::is_empty",
		description: "The array::is_empty function checks whether the array contains values.",
		signatures: &["array::is_empty(array) -> bool"],
	},
	BuiltinFn {
		name: "array::join",
		description: "The array::join function takes an array and a string as parameters and returns a concatenated string.",
		signatures: &["array::join(array, $concat_with: string) -> string"],
	},
	BuiltinFn {
		name: "array::last",
		description: "The array::last function returns the last value from an array.",
		signatures: &["array::last(array) -> any"],
	},
	BuiltinFn {
		name: "array::len",
		description: "The array::len function calculates the length of an array, returning a number. This function includes all items when counting the number of items in the array. If you want to only count truthy valu...",
		signatures: &["array::len(array) -> number"],
	},
	BuiltinFn {
		name: "array::logical_and",
		description: "The array::logical_and function performs the AND logical operation element-wise between two arrays. The resulting array will have a length of the longer of the two input arrays, where each element ...",
		signatures: &["array::logical_and($lh: array, $rh: array)"],
	},
	BuiltinFn {
		name: "array::logical_or",
		description: "The array::logical_or function performs the OR logical operations element-wise between two arrays.",
		signatures: &["array::logical_or($lh: array, $rh: array)"],
	},
	BuiltinFn {
		name: "array::logical_xor",
		description: "The array::logical_xor function performs the XOR logical operations element-wise between two arrays.",
		signatures: &["array::logical_xor($lh: array, $rh: array)"],
	},
	BuiltinFn {
		name: "array::map",
		description: "The array::map function allows the user to call an anonymous function (closure) that is performed on every item in the array before passing it on.",
		signatures: &["array::map(array, $operator: closure) -> array;"],
	},
	BuiltinFn {
		name: "array::matches",
		description: "The array::matches function returns an array of booleans indicating which elements of the input array contain a specified value.",
		signatures: &["array::matches(array, $predicate: value) -> array<bool>"],
	},
	BuiltinFn {
		name: "array::max",
		description: "The array::max function returns the greatest value from an array of values.",
		signatures: &["array::max(array<any>) -> any"],
	},
	BuiltinFn {
		name: "array::min",
		description: "The array::min function returns the least value from an array of values.",
		signatures: &["array::min(array<any>) -> any"],
	},
	BuiltinFn {
		name: "array::pop",
		description: "The array::pop function removes a value from the end of an array and returns it. If the array is empty, NONE is returned.",
		signatures: &["array::pop(array) -> value"],
	},
	BuiltinFn {
		name: "array::prepend",
		description: "The array::prepend function prepends a value to the beginning of an array.",
		signatures: &["array::prepend(array, $new_val: value) -> array"],
	},
	BuiltinFn {
		name: "array::push",
		description: "The array::push function appends a value to the end of an array.",
		signatures: &["array::push(array, $new_val: value) -> array"],
	},
	BuiltinFn {
		name: "array::range",
		description: "The array::range function creates an array of numbers from a given range.",
		signatures: &[
			"array::range($start: int, $end: int) -> array",
			"array::range(range) -> array;",
		],
	},
	BuiltinFn {
		name: "array::reduce",
		description: "The array::reduce function reduces the elements of an array to a single final value by allowing an operation to be performed at each step of the way as each subsequent item in the array is encounte...",
		signatures: &["array::reduce(array, $operator: closure) -> value"],
	},
	BuiltinFn {
		name: "array::remove",
		description: "The array::remove function removes an item from a specific position in an array. A negative index can be provided to specify a position relative to the end of the array.",
		signatures: &["array::remove(array, $index: number) -> array"],
	},
	BuiltinFn {
		name: "array::repeat",
		description: "The array::repeat function creates an array of a given size contain the specified value for each element.",
		signatures: &["array::repeat(any, $count: int) -> array"],
	},
	BuiltinFn {
		name: "array::reverse",
		description: "The array::reverse function reverses the sorting order of an array.",
		signatures: &["array::reverse(array) -> array"],
	},
	BuiltinFn {
		name: "array::sequence",
		description: "The array::sequence function creates an array of sequential integers.",
		signatures: &[
			"array::sequence($length: int) -> array",
			"array::sequence($start: int, $length: int) -> array",
		],
	},
	BuiltinFn {
		name: "array::shuffle",
		description: "The array::shuffle function randomly shuffles the items of an array.",
		signatures: &["array::shuffle(array) -> array"],
	},
	BuiltinFn {
		name: "array::slice",
		description: "The array::slice function returns a slice of an array, based on a starting position, and a length or negative position.",
		signatures: &[
			"array::slice(array, $start: int, $len: int) -> array",
			"array::slice(array, $slice: range) -> array;",
		],
	},
	BuiltinFn {
		name: "array::sort",
		description: "The array::sort function sorts the values in an array in ascending or descending order.",
		signatures: &[
			"array::sort(array) -> array",
			"array::sort(array, $asc: bool) -> array",
			"array::sort(array, $order: string) -> array",
		],
	},
	BuiltinFn {
		name: "array::sort::asc",
		description: "The array::sort::asc function is a shorthand convenience function for the array::sort function, to sort values in an array in ascending order.",
		signatures: &["array::sort::asc(array) -> array"],
	},
	BuiltinFn {
		name: "array::sort::desc",
		description: "The array::sort::desc function is a shorthand convenience function for the array::sort function, to sort values in an array in descending order.",
		signatures: &["array::sort::desc(array) -> array"],
	},
	BuiltinFn {
		name: "array::sort_lexical",
		description: "The array::sort_natural_lexical function sorts the values in an array in ascending or descending order, with alphabetical strings sorted in lexical order instead of unicode list order.",
		signatures: &[
			"array::sort_lexical(array) -> array",
			"array::sort_lexical(array, $asc: bool) -> array",
			"array::sort_lexical(array, $order: string) -> array",
		],
	},
	BuiltinFn {
		name: "array::sort_natural",
		description: "The array::sort_natural function sorts the values in an array in ascending or descending order, with numeric strings sorted in numeric order instead of regular string order.",
		signatures: &[
			"array::sort_natural(array) -> array",
			"array::sort_natural(array, $asc: bool) -> array",
			"array::sort_natural(array, $order: string) -> array",
		],
	},
	BuiltinFn {
		name: "array::sort_natural_lexical",
		description: "The array::sort_natural_lexical function sorts the values in an array in ascending or descending order, while sorting numeric strings in numeric order and alphabetical strings in lexical order.",
		signatures: &[
			"array::sort_natural_lexical(array) -> array",
			"array::sort_natural_lexical(array, $asc: bool) -> array",
			"array::sort_natural_lexical(array, $order: string) -> array",
		],
	},
	BuiltinFn {
		name: "array::swap",
		description: "The array::swap function swaps two values of an array based on indexes.",
		signatures: &["array::swap(array, $from: int, $to: int) -> array"],
	},
	BuiltinFn {
		name: "array::transpose",
		description: "The array::transpose function is used to perform 2d array transposition but its behavior in cases of arrays of differing sizes can be best described as taking in multiple arrays and 'layering' them...",
		signatures: &["array::transpose(array<array>) -> array<array>"],
	},
	BuiltinFn {
		name: "array::union",
		description: "The array::union function combines two arrays together, removing duplicate values, and returning a single array.",
		signatures: &["array::union(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "array::windows",
		description: "Built-in function array::windows",
		signatures: &["array::windows(array, $window_size: int) -> array"],
	},
	BuiltinFn {
		name: "bytes::len",
		description: "The bytes::len function returns the length in bytes of a bytes value.",
		signatures: &["bytes::len(bytes) -> int"],
	},
	BuiltinFn {
		name: "crypto::argon2::compare",
		description: "The crypto::argon2::compare function compares a hashed-and-salted argon2 password value with an unhashed password value.",
		signatures: &["crypto::argon2::compare(string, $against: string) -> bool"],
	},
	BuiltinFn {
		name: "crypto::argon2::generate",
		description: "The crypto::argon2::generate function hashes and salts a password using the argon2 hashing algorithm.",
		signatures: &["crypto::argon2::generate(string) -> string"],
	},
	BuiltinFn {
		name: "crypto::bcrypt::compare",
		description: "The crypto::bcrypt::compare function compares a hashed-and-salted bcrypt password value with an unhashed password value.",
		signatures: &["crypto::bcrypt::compare(string, $against: string) -> bool"],
	},
	BuiltinFn {
		name: "crypto::bcrypt::generate",
		description: "The crypto::bcrypt::generate function hashes and salts a password using the bcrypt hashing algorithm.",
		signatures: &["crypto::bcrypt::generate(string) -> string"],
	},
	BuiltinFn {
		name: "crypto::blake3",
		description: "The crypto::blake3 function returns the blake3 hash of the input value.",
		signatures: &["crypto::blake3(string) -> string"],
	},
	BuiltinFn {
		name: "crypto::joaat",
		description: "The crypto::joaat function returns the joaat hash of the input value.",
		signatures: &["crypto::joaat(string) -> number"],
	},
	BuiltinFn {
		name: "crypto::md5",
		description: "The crypto::md5 function returns the md5 hash of the input value.",
		signatures: &["crypto::md5(string) -> string"],
	},
	BuiltinFn {
		name: "crypto::pbkdf2::compare",
		description: "The crypto::pbkdf2::compare function compares a hashed-and-salted pbkdf2 password value with an unhashed password value.",
		signatures: &["crypto::pbkdf2::compare(string, $against: string) -> bool"],
	},
	BuiltinFn {
		name: "crypto::pbkdf2::generate",
		description: "The crypto::pbkdf2::generate function hashes and salts a password using the pbkdf2 hashing algorithm.",
		signatures: &["crypto::pbkdf2::generate(string) -> string"],
	},
	BuiltinFn {
		name: "crypto::scrypt::compare",
		description: "The crypto::scrypt::compare function compares a hashed-and-salted scrypt password value with an unhashed password value.",
		signatures: &["crypto::scrypt::compare(string, $against: string) -> bool"],
	},
	BuiltinFn {
		name: "crypto::scrypt::generate",
		description: "The crypto::scrypt::generate function hashes and salts a password using the scrypt hashing algorithm.",
		signatures: &["crypto::scrypt::generate(string) -> string"],
	},
	BuiltinFn {
		name: "crypto::sha1",
		description: "The crypto::sha1 function returns the sha1 hash of the input value.",
		signatures: &["crypto::sha1(string) -> string"],
	},
	BuiltinFn {
		name: "crypto::sha256",
		description: "The crypto::sha256 function returns the sha256 hash of the input value.",
		signatures: &["crypto::sha256(string) -> string"],
	},
	BuiltinFn {
		name: "crypto::sha512",
		description: "The crypto::sha512 function returns the sha512 hash of the input value.",
		signatures: &["crypto::sha512(string) -> string"],
	},
	BuiltinFn {
		name: "duration::days",
		description: "The duration::days function counts how many days fit into a duration.",
		signatures: &["duration::days(duration) -> number"],
	},
	BuiltinFn {
		name: "duration::from_days",
		description: "The duration::from_days function counts how many years fit into a duration.",
		signatures: &["duration::from_days(number) -> duration"],
	},
	BuiltinFn {
		name: "duration::from_hours",
		description: "The duration::from_hours function converts a numeric amount of hours into a duration that represents hours.",
		signatures: &["duration::from_hours(number) -> duration"],
	},
	BuiltinFn {
		name: "duration::from_micros",
		description: "The duration::from_micros function converts a numeric amount of microseconds into a duration that represents microseconds.",
		signatures: &["duration::from_micros(number) -> duration"],
	},
	BuiltinFn {
		name: "duration::from_millis",
		description: "The duration::from_millis function converts a numeric amount of milliseconds into a duration that represents milliseconds.",
		signatures: &["duration::from_millis(number) -> duration"],
	},
	BuiltinFn {
		name: "duration::from_mins",
		description: "The duration::from_mins function converts a numeric amount of minutes into a duration that represents minutes.",
		signatures: &["duration::from_mins(number) -> duration"],
	},
	BuiltinFn {
		name: "duration::from_nanos",
		description: "The duration::from_nanos function converts a numeric amount of nanoseconds into a duration that represents nanoseconds.",
		signatures: &["duration::from_nanos(number) -> duration"],
	},
	BuiltinFn {
		name: "duration::from_secs",
		description: "The duration::from_secs function converts a numeric amount of seconds into a duration that represents seconds.",
		signatures: &["duration::from_secs(number) -> duration"],
	},
	BuiltinFn {
		name: "duration::from_weeks",
		description: "The duration::from_weeks function converts a numeric amount of weeks into a duration that represents weeks.",
		signatures: &["duration::from_weeks(number) -> duration"],
	},
	BuiltinFn {
		name: "duration::hours",
		description: "The duration::hours function counts how many hours fit into a duration.",
		signatures: &["duration::hours(duration) -> number"],
	},
	BuiltinFn {
		name: "duration::max",
		description: "The duration::max constant represents the greatest possible duration that can be used.",
		signatures: &["duration::max -> duration"],
	},
	BuiltinFn {
		name: "duration::micros",
		description: "The duration::micros function counts how many microseconds fit into a duration.",
		signatures: &["duration::micros(duration) -> number"],
	},
	BuiltinFn {
		name: "duration::millis",
		description: "The duration::millis function counts how many milliseconds fit into a duration.",
		signatures: &["duration::millis(duration) -> number"],
	},
	BuiltinFn {
		name: "duration::mins",
		description: "The duration::mins function counts how many minutes fit into a duration.",
		signatures: &["duration::mins(duration) -> number"],
	},
	BuiltinFn {
		name: "duration::nanos",
		description: "The duration::nanos function counts how many nanoseconds fit into a duration.",
		signatures: &["duration::nanos(duration) -> number"],
	},
	BuiltinFn {
		name: "duration::secs",
		description: "The duration::secs function counts how many seconds fit into a duration.",
		signatures: &["duration::secs(duration) -> number"],
	},
	BuiltinFn {
		name: "duration::weeks",
		description: "The duration::weeks function counts how many weeks fit into a duration.",
		signatures: &["duration::weeks(duration) -> number"],
	},
	BuiltinFn {
		name: "duration::years",
		description: "The duration::years function counts how many years fit into a duration.",
		signatures: &["duration::years(duration) -> number"],
	},
	BuiltinFn {
		name: "file::bucket",
		description: "Built-in function file::bucket",
		signatures: &["file::bucket(file) -> string"],
	},
	BuiltinFn {
		name: "file::copy",
		description: "The file::copy function copies the contents of a file to a new file, overwriting any existing file that has the same name as the new file.",
		signatures: &["file::copy(string)"],
	},
	BuiltinFn {
		name: "file::copy_if_not_exists",
		description: "The file::copy_if_not_exists function copies the contents of a file to a new file, returning an error if a file already exists that has the same name as that of the intended copy.",
		signatures: &["file::copy_if_not_exists(string)"],
	},
	BuiltinFn {
		name: "file::delete",
		description: "The file::delete function deletes a file.",
		signatures: &["file::delete(string)"],
	},
	BuiltinFn {
		name: "file::exists",
		description: "The file::exists function checks to see if a file exists at the path and file name indicated.",
		signatures: &["file::exists(string) -> bool"],
	},
	BuiltinFn {
		name: "file::get",
		description: "The file::get function retrieves a file for use.",
		signatures: &["file::get(string) -> bytes"],
	},
	BuiltinFn {
		name: "file::head",
		description: "The file::head function returns the metadata for a file.",
		signatures: &["file::head() -> object"],
	},
	BuiltinFn {
		name: "file::key",
		description: "Built-in function file::key",
		signatures: &["file::key(file) -> string"],
	},
	BuiltinFn {
		name: "file::list",
		description: "Built-in function file::list",
		signatures: &["file::list(string, $list_options: option<object>) -> array<object>"],
	},
	BuiltinFn {
		name: "file::put",
		description: "The file::put function adds data into a file, overwriting any existing data.",
		signatures: &["file::put()"],
	},
	BuiltinFn {
		name: "file::put_if_not_exists",
		description: "The file::put function adds data into a file, unless a file of the same name already exists.",
		signatures: &["file::put_if_not_exists()"],
	},
	BuiltinFn {
		name: "file::rename",
		description: "The file::rename function renames a file, overwriting any existing file that has the same name as the target name.",
		signatures: &["file::rename()"],
	},
	BuiltinFn {
		name: "file::rename_if_not_exists",
		description: "The file::rename_if_not_exists function renames a file, returning an error if a file already exists that has the same name as the target name.",
		signatures: &["file::rename_if_not_exists()"],
	},
	BuiltinFn {
		name: "geo::area",
		description: "The geo::area function calculates the area of a geometry in square metres.",
		signatures: &["geo::area(geometry) -> number"],
	},
	BuiltinFn {
		name: "geo::bearing",
		description: "The geo::bearing function calculates the bearing between two geolocation points. Bearing begins at 0 degrees to indicate north, increasing clockwise into positive values and decreasing counterclock...",
		signatures: &["geo::bearing($from: point, $to: point) -> number"],
	},
	BuiltinFn {
		name: "geo::centroid",
		description: "The geo::centroid function calculates the centroid between multiple geolocation points.",
		signatures: &["geo::centroid(geometry) -> number"],
	},
	BuiltinFn {
		name: "geo::distance",
		description: "The geo::distance function calculates the haversine distance, in metres, between two geolocation points.",
		signatures: &["geo::distance($from: point, $to: point) -> number"],
	},
	BuiltinFn {
		name: "geo::hash::decode",
		description: "The geo::hash::decode function converts a geohash into a geolocation point.",
		signatures: &["geo::hash::decode(point) -> string"],
	},
	BuiltinFn {
		name: "geo::hash::encode",
		description: "The geo::hash::encode function converts a geolocation point into a geohash.",
		signatures: &[
			"geo::hash::encode(point) -> string",
			"geo::hash::encode(point, $granularity: number) -> string",
		],
	},
	BuiltinFn {
		name: "geo::is_valid",
		description: "The geo::is_valid function determines if a geometry type is a geography type. Geography types are used to store geolocation data in a Geographic Coordinate System (GCS), whereas geometry types can ...",
		signatures: &["geo::is_valid(geometry) -> bool"],
	},
	BuiltinFn {
		name: "http::delete",
		description: "The http::delete function performs a remote HTTP DELETE request. The first parameter is the URL of the remote endpoint, and the second parameter is the value to use as the request body, which will ...",
		signatures: &[
			"http::delete(string) -> value",
			"http::delete(string, $headers: object) -> value",
		],
	},
	BuiltinFn {
		name: "http::get",
		description: "The http::get function performs a remote HTTP GET request. The first parameter is the URL of the remote endpoint. If the response does not return a 2XX status code, then the function will fail and ...",
		signatures: &[
			"http::get(string) -> value",
			"http::get(string, $headers: object) -> value",
		],
	},
	BuiltinFn {
		name: "http::head",
		description: "The http::head function performs a remote HTTP HEAD request. The first parameter is the URL of the remote endpoint. If the response does not return a 2XX status code, then the function will fail an...",
		signatures: &[
			"http::head(string) -> null",
			"http::head(string, $headers: object) -> null",
		],
	},
	BuiltinFn {
		name: "http::patch",
		description: "The http::patch function performs a remote HTTP PATCH request. The first parameter is the URL of the remote endpoint, and the second parameter is the value to use as the request body, which will be...",
		signatures: &[
			"http::patch(string, $body: object) -> value",
			"http::patch(string, $body: object, $headers: object) -> value",
		],
	},
	BuiltinFn {
		name: "http::post",
		description: "The http::post function performs a remote HTTP POST request. The first parameter is the URL of the remote endpoint, and the second parameter is the value to use as the request body, which will be c...",
		signatures: &[
			"http::post(string, $body: object) -> value",
			"http::post(string, $body: object, $headers: object) -> value",
		],
	},
	BuiltinFn {
		name: "http::put",
		description: "The http::put function performs a remote HTTP PUT request. The first parameter is the URL of the remote endpoint, and the second parameter is the value to use as the request body, which will be con...",
		signatures: &[
			"http::put(string, $body: object) -> value",
			"http::put(string, $body: object, $headers: object) -> value",
		],
	},
	BuiltinFn {
		name: "math::abs",
		description: "The math::abs function returns the absolute value of a number.",
		signatures: &["math::abs(number) -> number"],
	},
	BuiltinFn {
		name: "math::acos",
		description: "The math::acos function returns the arccosine (inverse cosine) of a number, which must be in the range -1 to 1. The result is expressed in radians.",
		signatures: &["math::acos(number) -> number"],
	},
	BuiltinFn {
		name: "math::acot",
		description: "The math::acot function returns the arccotangent (inverse cotangent) of a number. The result is expressed in radians.",
		signatures: &["math::acot(number) -> number"],
	},
	BuiltinFn {
		name: "math::asin",
		description: "The math::asin function returns the arcsine (inverse sine) of a number, which must be in the range -1 to 1. The result is expressed in radians.",
		signatures: &["math::asin(number) -> number"],
	},
	BuiltinFn {
		name: "math::atan",
		description: "The math::atan function returns the arctangent (inverse tangent) of a number. The result is expressed in radians.",
		signatures: &["math::atan(number) -> number"],
	},
	BuiltinFn {
		name: "math::bottom",
		description: "The math::bottom function returns the bottom X set of numbers in an array of numbers.",
		signatures: &["math::bottom(array<number>, $quantity: number) -> number"],
	},
	BuiltinFn {
		name: "math::ceil",
		description: "The math::ceil function rounds a number up to the next largest whole number.",
		signatures: &["math::ceil(number) -> number"],
	},
	BuiltinFn {
		name: "math::clamp",
		description: "The math::clamp function constrains a number within the specified range, defined by a minimum and a maximum value. If the number is less than the minimum, it returns the minimum. If it is greater t...",
		signatures: &["math::clamp(number, $min: number, $max: number) -> number"],
	},
	BuiltinFn {
		name: "math::cos",
		description: "The math::cos function returns the cosine of a number, which is assumed to be in radians. The result is a value between -1 and 1.",
		signatures: &["math::cos(number) -> number"],
	},
	BuiltinFn {
		name: "math::cot",
		description: "The math::cot function returns the cotangent of a number, which is assumed to be in radians. The cotangent is the reciprocal of the tangent function.",
		signatures: &["math::cot(number) -> number"],
	},
	BuiltinFn {
		name: "math::deg2rad",
		description: "The math::deg2rad function converts an angle from degrees to radians.",
		signatures: &["math::deg2rad(number) -> number"],
	},
	BuiltinFn {
		name: "math::e",
		description: "The math::e constant represents the base of the natural logarithm (Euler’s number).",
		signatures: &["math::e -> number"],
	},
	BuiltinFn {
		name: "math::fixed",
		description: "The math::fixed function returns a number with the specified number of decimal places.",
		signatures: &["math::fixed(number, $places: number) -> number"],
	},
	BuiltinFn {
		name: "math::floor",
		description: "The math::floor function rounds a number down to the nearest integer.",
		signatures: &["math::floor(number) -> number"],
	},
	BuiltinFn {
		name: "math::frac_1_pi",
		description: "The math::frac_1_pi constant represents the fraction 1/π.",
		signatures: &["math::frac_1_pi -> number"],
	},
	BuiltinFn {
		name: "math::frac_1_sqrt_2",
		description: "The math::frac_1_sqrt_2 constant represents the fraction 1/sqrt(2).",
		signatures: &["math::frac_1_sqrt_2 -> number"],
	},
	BuiltinFn {
		name: "math::frac_2_pi",
		description: "The math::frac_2_pi constant represents the fraction 2/π.",
		signatures: &["math::frac_2_pi -> number"],
	},
	BuiltinFn {
		name: "math::frac_2_sqrt_pi",
		description: "The math::frac_2_sqrt_pi constant represents the fraction 2/sqrt(π).",
		signatures: &["math::frac_2_sqrt_pi -> number"],
	},
	BuiltinFn {
		name: "math::frac_pi_2",
		description: "The math::frac_pi_2 constant represents the fraction π/2.",
		signatures: &["math::frac_pi_2 -> number"],
	},
	BuiltinFn {
		name: "math::frac_pi_3",
		description: "The math::frac_pi_3 constant represents the fraction π/3.",
		signatures: &["math::frac_pi_3 -> number"],
	},
	BuiltinFn {
		name: "math::frac_pi_4",
		description: "The math::frac_pi_4 constant represents the fraction π/4.",
		signatures: &["math::frac_pi_4 -> number"],
	},
	BuiltinFn {
		name: "math::frac_pi_6",
		description: "The math::frac_pi_6 constant represents the fraction π/6.",
		signatures: &["math::frac_pi_6 -> number"],
	},
	BuiltinFn {
		name: "math::frac_pi_8",
		description: "The math::frac_pi_8 constant represents the fraction π/8.",
		signatures: &["math::frac_pi_8 -> number"],
	},
	BuiltinFn {
		name: "math::inf",
		description: "The math::inf constant represents positive infinity.",
		signatures: &["math::inf -> number"],
	},
	BuiltinFn {
		name: "math::interquartile",
		description: "The math::interquartile function returns the interquartile of an array of numbers.",
		signatures: &["math::interquartile(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::lerp",
		description: "The math::lerp function performs a linear interpolation between two numbers based on a given fraction. The fraction will usually be between 0 and 1, where 0 returns $num_1 and 1 returns $num_2.",
		signatures: &["math::lerp($num_1: number, $num_2: number, $fraction: number) -> number"],
	},
	BuiltinFn {
		name: "math::lerpangle",
		description: "The math::lerpangle function interpolates between two angles ($num_1 and $num_2) by the given fraction. This is useful for smoothly transitioning between angles.",
		signatures: &[
			"math::lerpangle($num_1: number, $num_2: number, $fraction: number) -> number",
		],
	},
	BuiltinFn {
		name: "math::ln",
		description: "The math::ln function returns the natural logarithm (base e) of a number.",
		signatures: &["math::ln(number) -> number"],
	},
	BuiltinFn {
		name: "math::ln_10",
		description: "The math::ln_10 constant represents the natural logarithm (base e) of 10.",
		signatures: &["math::ln_10 -> number"],
	},
	BuiltinFn {
		name: "math::ln_2",
		description: "The math::ln_2 constant represents the natural logarithm (base e) of 2.",
		signatures: &["math::ln_2 -> number"],
	},
	BuiltinFn {
		name: "math::log",
		description: "The math::log function returns the logarithm of a number with a specified base.",
		signatures: &["math::log(number, $base: number) -> number"],
	},
	BuiltinFn {
		name: "math::log10",
		description: "The math::log10 function returns the base-10 logarithm of a number.",
		signatures: &["math::log10(number) -> number"],
	},
	BuiltinFn {
		name: "math::log10_2",
		description: "The math::log10_2 constant represents the base-10 logarithm of 2.",
		signatures: &["math::log10_2 -> number"],
	},
	BuiltinFn {
		name: "math::log10_e",
		description: "The math::log10_e constant represents the base-10 logarithm of e, the base of the natural logarithm (Euler’s number).",
		signatures: &["math::log10_e -> number"],
	},
	BuiltinFn {
		name: "math::log2",
		description: "The math::log2 function returns the base-2 logarithm of a number.",
		signatures: &["math::log2(number) -> number"],
	},
	BuiltinFn {
		name: "math::log2_10",
		description: "The math::log2_10 constant represents the base-2 logarithm of 10.",
		signatures: &["math::log2_10 -> number"],
	},
	BuiltinFn {
		name: "math::log2_e",
		description: "The math::log2_e constant represents the base-2 logarithm of e, the base of the natural logarithm (Euler’s number).",
		signatures: &["math::log2_e -> number"],
	},
	BuiltinFn {
		name: "math::max",
		description: "The math::max function returns the greatest number from an array of numbers.",
		signatures: &["math::max(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::mean",
		description: "The math::mean function returns the mean of a set of numbers.",
		signatures: &["math::mean(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::median",
		description: "The math::median function returns the median of a set of numbers.",
		signatures: &["math::median(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::midhinge",
		description: "The math::midhinge function returns the midhinge of an array of numbers.",
		signatures: &["math::midhinge(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::min",
		description: "The math::min function returns the least number from an array of numbers.",
		signatures: &["math::min(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::mode",
		description: "The math::mode function returns the value that occurs most often in a set of numbers. In case of a tie, the highest one is returned.",
		signatures: &["math::mode(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::nearestrank",
		description: "The math::nearestrank function returns the nearest rank of an array of numbers by pullinng the closest extant record from the dataset at the %-th percentile.",
		signatures: &["math::nearestrank(array<number>, $percentile: number) -> number"],
	},
	BuiltinFn {
		name: "math::neg_inf",
		description: "The math::neg_inf constant represents negative infinity.",
		signatures: &["math::neg_inf -> number"],
	},
	BuiltinFn {
		name: "math::percentile",
		description: "The math::percentile function returns the value below which a percentage of data falls by getting the N percentile, averaging neighboring records if non-exact.",
		signatures: &["math::percentile(array<number>, $percentile: number) -> number"],
	},
	BuiltinFn {
		name: "math::pi",
		description: "The math::pi constant represents the mathematical constant π.",
		signatures: &["math::pi -> number"],
	},
	BuiltinFn {
		name: "math::pow",
		description: "The math::pow function returns a number raised to the power of a second number.",
		signatures: &["math::pow(number, $raise_to: number) -> number"],
	},
	BuiltinFn {
		name: "math::product",
		description: "The math::product function returns the product of a set of numbers.",
		signatures: &["math::product(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::rad2deg",
		description: "The math::rad2deg function converts an angle from radians to degrees.",
		signatures: &["math::rad2deg(number) -> number"],
	},
	BuiltinFn {
		name: "math::round",
		description: "The math::round function rounds a number up or down to the nearest integer.",
		signatures: &["math::round(number) -> number"],
	},
	BuiltinFn {
		name: "math::sign",
		description: "The math::sign function returns the sign of a number, indicating whether the number is positive, negative, or zero. It returns 1 for positive numbers, -1 for negative numbers, and 0 for zero.",
		signatures: &["math::sign(number) -> number"],
	},
	BuiltinFn {
		name: "math::sin",
		description: "The math::sin function returns the sine of a number, which is assumed to be in radians.",
		signatures: &["math::sin(number) -> number"],
	},
	BuiltinFn {
		name: "math::spread",
		description: "The math::spread function returns the spread of an array of numbers.",
		signatures: &["math::spread(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::sqrt",
		description: "The math::sqrt function returns the square root of a number.",
		signatures: &["math::sqrt(number) -> number"],
	},
	BuiltinFn {
		name: "math::sqrt_2",
		description: "The math::sqrt_2 constant represents the square root of 2.",
		signatures: &["math::sqrt_2 -> number"],
	},
	BuiltinFn {
		name: "math::stddev",
		description: "The math::stddev function calculates how far a set of numbers are away from the mean.",
		signatures: &["math::stddev(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::sum",
		description: "The math::sum function returns the total sum of a set of numbers.",
		signatures: &["math::sum(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::tan",
		description: "The math::tan function returns the tangent of a number, which is assumed to be in radians.",
		signatures: &["math::tan(number) -> number"],
	},
	BuiltinFn {
		name: "math::tau",
		description: "The math::tau constant represents the mathematical constant τ, which is equal to 2π.",
		signatures: &["math::tau -> number"],
	},
	BuiltinFn {
		name: "math::top",
		description: "The math::top function returns the top of an array of numbers.",
		signatures: &["math::top(array<number>, $quantity: number) -> number"],
	},
	BuiltinFn {
		name: "math::trimean",
		description: "The math::trimean function returns the trimean of an array of numbers.",
		signatures: &["math::trimean(array<number>) -> number"],
	},
	BuiltinFn {
		name: "math::variance",
		description: "The math::variance function returns the variance of an array of numbers.",
		signatures: &["math::variance(array<number>) -> number"],
	},
	BuiltinFn {
		name: "meta::id",
		description: "The meta::id function extracts and returns the identifier from a SurrealDB Record ID.",
		signatures: &["meta::id(record) -> value"],
	},
	BuiltinFn {
		name: "meta::tb",
		description: "The meta::tb function extracts and returns the table name from a SurrealDB Record ID.",
		signatures: &["meta::tb(record) -> string"],
	},
	BuiltinFn {
		name: "object::entries",
		description: "The object::entries function transforms an object into an array with arrays of key-value combinations.",
		signatures: &["object::entries(object) -> array"],
	},
	BuiltinFn {
		name: "object::extend",
		description: "The object::extend function extends an object with the fields and values of another one, essentially adding the two together.",
		signatures: &["object::extend(object, $other: object) -> object"],
	},
	BuiltinFn {
		name: "object::from_entries",
		description: "The object::from_entries function transforms an array with arrays of key-value combinations into an object.",
		signatures: &["object::from_entries(array) -> object"],
	},
	BuiltinFn {
		name: "object::is_empty",
		description: "The object::is_empty function checks whether the object contains values.",
		signatures: &["object::is_empty(object) -> bool"],
	},
	BuiltinFn {
		name: "object::keys",
		description: "The object::keys function returns an array with all the keys of an object.",
		signatures: &["object::keys(object) -> array"],
	},
	BuiltinFn {
		name: "object::len",
		description: "The object::len function returns the amount of key-value pairs an object holds.",
		signatures: &["object::len(object) -> number"],
	},
	BuiltinFn {
		name: "object::remove",
		description: "The object::remove function removes one or more fields from an object.",
		signatures: &["object::remove(object, $to_remove: string|array<string>) -> object"],
	},
	BuiltinFn {
		name: "object::values",
		description: "The object::values function returns an array with all the values of an object.",
		signatures: &["object::values(object) -> array"],
	},
	BuiltinFn {
		name: "parse::email::host",
		description: "The parse::email::host function parses and returns an email host from a valid email address.",
		signatures: &["parse::email::host(string) -> string"],
	},
	BuiltinFn {
		name: "parse::email::user",
		description: "The parse::email::user function parses and returns an email username from a valid email address.",
		signatures: &["parse::email::user(string) -> string"],
	},
	BuiltinFn {
		name: "parse::url::domain",
		description: "The parse::url::domain function parses and returns domain from a valid URL. This function is similar to parse::url::host only that it will return null if the URL is an IP address.",
		signatures: &["parse::url::domain(string) -> string"],
	},
	BuiltinFn {
		name: "parse::url::fragment",
		description: "The parse::url::fragment function parses and returns the fragment from a valid URL.",
		signatures: &["parse::url::fragment(string) -> string"],
	},
	BuiltinFn {
		name: "parse::url::host",
		description: "The parse::url::host function parses and returns the hostname from a valid URL.",
		signatures: &["parse::url::host(string) -> string"],
	},
	BuiltinFn {
		name: "parse::url::path",
		description: "The parse::url::path  function parses and returns the path from a valid URL.",
		signatures: &["parse::url::path(string) -> string"],
	},
	BuiltinFn {
		name: "parse::url::port",
		description: "The parse::url::port function parses and returns the port from a valid URL.",
		signatures: &["parse::url::port(string) -> number"],
	},
	BuiltinFn {
		name: "parse::url::query",
		description: "The parse::url::query function parses and returns the query from a valid URL.",
		signatures: &["parse::url::query(string) -> string"],
	},
	BuiltinFn {
		name: "parse::url::scheme",
		description: "The parse::url::scheme function parses and returns the scheme from a valid URL, in lowercase, as an ASCII string without the ':' delimiter.",
		signatures: &["parse::url::scheme(string) -> string"],
	},
	BuiltinFn {
		name: "rand::bool",
		description: "The rand::bool function generates a random boolean value.",
		signatures: &["rand::bool() -> bool"],
	},
	BuiltinFn {
		name: "rand::duration",
		description: "The rand::duration function generates a random duration value between two duration arguments.",
		signatures: &["rand::bool($from: duration, $to: duration) -> duration"],
	},
	BuiltinFn {
		name: "rand::enum",
		description: "The rand::enum function generates a random value, from a multitude of values.",
		signatures: &[
			"rand::enum(value...) -> any",
			"rand::enum(array<value>) -> any",
		],
	},
	BuiltinFn {
		name: "rand::float",
		description: "The rand::float function generates a random float, between 0 and 1.",
		signatures: &[
			"rand::float() -> float",
			"rand::float($from: number, $to: number) -> float",
		],
	},
	BuiltinFn {
		name: "rand::id",
		description: "> [!NOTE] > This function was known as rand::guid in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &[
			"rand::id() -> string",
			"rand::id(number) -> string",
			"rand::id($min_len: int, $max_len: int) -> string",
		],
	},
	BuiltinFn {
		name: "rand::int",
		description: "The rand::int function generates a random int.",
		signatures: &[
			"rand::int() -> int",
			"rand::int($from: int, $to: int) -> int",
		],
	},
	BuiltinFn {
		name: "rand::string",
		description: "The rand::string function generates a random string, with 32 characters.",
		signatures: &[
			"rand::string() -> string",
			"rand::string(number) -> string",
			"rand::string($from: int, $to: int) -> string",
		],
	},
	BuiltinFn {
		name: "rand::time",
		description: "The rand::time function generates a random datetime.",
		signatures: &[
			"rand::time() -> datetime",
			"rand::time($from: datetime|number, $to: datetime|number) -> datetime",
		],
	},
	BuiltinFn {
		name: "rand::ulid",
		description: "The rand::ulid function generates a random ULID.",
		signatures: &["rand::ulid() -> uuid", "rand::ulid(datetime) -> uuid"],
	},
	BuiltinFn {
		name: "rand::uuid",
		description: "The rand::uuid function generates a random Version 7 UUID.",
		signatures: &["rand::uuid() -> uuid", "rand::uuid(datetime) -> uuid"],
	},
	BuiltinFn {
		name: "rand::uuid::v4",
		description: "The rand::uuid::v4 function generates a random version 4 UUID.",
		signatures: &["rand::uuid::v4() -> uuid"],
	},
	BuiltinFn {
		name: "record::exists",
		description: "The record::exists function checks to see if a given record exists.",
		signatures: &["record::exists(record) -> bool"],
	},
	BuiltinFn {
		name: "record::id",
		description: "The record::id function extracts and returns the identifier from a SurrealDB Record ID.",
		signatures: &["record::id(record) -> value"],
	},
	BuiltinFn {
		name: "record::is_edge",
		description: "The record::is_edge function checks to see if the value passed in is a graph edge.",
		signatures: &["record::is_edge(record | string) -> bool"],
	},
	BuiltinFn {
		name: "record::tb",
		description: "The record::tb function extracts and returns the table name from a SurrealDB Record ID.",
		signatures: &["record::tb(record) -> string"],
	},
	BuiltinFn {
		name: "search::analyze",
		description: "The search_analyze function returns the outut of a defined search analyzer on an input string.",
		signatures: &["search::analyze($analyzer: string, $input: string) -> array<string>"],
	},
	BuiltinFn {
		name: "search::highlight",
		description: "The search::highlight function highlights the matching keywords for the predicate reference number.",
		signatures: &[
			"search::highlight($prepend: string, $append: string, $predicate: number, $highlight_all: option<bool>) -> string | string[]",
		],
	},
	BuiltinFn {
		name: "search::linear",
		description: "Built-in function search::linear",
		signatures: &[
			"search::linear($lists: array, $weights: array, $limit: int, $norm: 'minmax' | 'zscore') -> array<object>",
		],
	},
	BuiltinFn {
		name: "search::offsets",
		description: "The search::offsets function returns the position of the matching keywords for the predicate reference number.",
		signatures: &[
			"search::offsets($predicate: number, $highlight_all: option<bool>) -> object",
		],
	},
	BuiltinFn {
		name: "search::rrf",
		description: "Built-in function search::rrf",
		signatures: &["search::rrf($lists: array, $limit: int, $k: option<int>) -> array<object>"],
	},
	BuiltinFn {
		name: "search::score",
		description: "The search::score function returns the relevance score corresponding to the given 'matches' predicate reference numbers.",
		signatures: &["search::score(number) -> number"],
	},
	BuiltinFn {
		name: "sequence::next",
		description: "The sequence::next function returns the next value in a sequence.",
		signatures: &["sequence::next($seq_name: string) -> int"],
	},
	BuiltinFn {
		name: "session::ac",
		description: "> [!NOTE] > This function was known as session::sc in versions of SurrrealDB before 2.0. The behaviour has not changed.",
		signatures: &["session::ac() -> string"],
	},
	BuiltinFn {
		name: "session::db",
		description: "The session::db function returns the currently selected database.",
		signatures: &["session::db() -> string"],
	},
	BuiltinFn {
		name: "session::id",
		description: "The session::id function returns the current user's session ID.",
		signatures: &["session::id() -> string"],
	},
	BuiltinFn {
		name: "session::ip",
		description: "The session::ip function returns the current user's session IP address.",
		signatures: &["session::ip() -> string"],
	},
	BuiltinFn {
		name: "session::ns",
		description: "The session::ns function returns the currently selected namespace.",
		signatures: &["session::ns() -> string"],
	},
	BuiltinFn {
		name: "session::origin",
		description: "The session::origin function returns the current user's HTTP origin.",
		signatures: &["session::origin() -> string"],
	},
	BuiltinFn {
		name: "session::rd",
		description: "The session::rd function returns the current user's record authentication.",
		signatures: &["session::rd() -> string"],
	},
	BuiltinFn {
		name: "session::token",
		description: "The session::token function returns the current authentication token.",
		signatures: &["session::token() -> string"],
	},
	BuiltinFn {
		name: "set::add",
		description: "The set::add function adds an item to a set only if it does not already exist.",
		signatures: &["set::add(set, $new_val: value) -> set"],
	},
	BuiltinFn {
		name: "set::all",
		description: "When called on a set without any extra arguments, the set::all function checks whether all set values are truthy.",
		signatures: &[
			"set::all(set) -> bool",
			"set::all(set, $predicate: value) -> bool",
			"set::all(set, $predicate: closure) -> bool",
		],
	},
	BuiltinFn {
		name: "set::any",
		description: "The set::any function checks whether any set values are truthy.",
		signatures: &[
			"set::any(set) -> bool",
			"set::any(set, $predicate: value) -> bool",
			"set::any(set, $predicate: closure) -> bool",
		],
	},
	BuiltinFn {
		name: "set::at",
		description: "The set::at function returns the value at the specified only, or in reverse for a negative index.",
		signatures: &["set::at(set, $index: int) -> any"],
	},
	BuiltinFn {
		name: "set::complement",
		description: "The set::complement function returns the complement of two sets, namely a single set containing items that are in the first set but not in the second set.",
		signatures: &["set::complement(set, $other: set) -> set"],
	},
	BuiltinFn {
		name: "set::contains",
		description: "The set::contains function checks to see if a value is contained within a set.",
		signatures: &["set::contains(set, $other: value) -> bool"],
	},
	BuiltinFn {
		name: "set::difference",
		description: "The set::difference function determines the symmetric difference between two sets, returning a single set containing items that are not shared between them.",
		signatures: &["set::difference(set, $other: set) -> set"],
	},
	BuiltinFn {
		name: "set::filter",
		description: "The set::filter function filters out values that do not match a pattern.",
		signatures: &[
			"set::filter(set, $predicate: value) -> set",
			"set::filter(set, $predicate: closure) -> set",
		],
	},
	BuiltinFn {
		name: "set::find",
		description: "The set::find function returns the first matching value from a set.",
		signatures: &[
			"set::find(set, $predicate: value) -> value | NONE",
			"set::find(set, $predicate: closure) -> value | NONE",
		],
	},
	BuiltinFn {
		name: "set::first",
		description: "The set::first function returns the first value from a set.",
		signatures: &["set::first(set) -> any"],
	},
	BuiltinFn {
		name: "set::flatten",
		description: "The set::flatten function flattens nested sets and arrays into a single set.",
		signatures: &["set::flatten(set) -> set"],
	},
	BuiltinFn {
		name: "set::fold",
		description: "The set::fold function applies an operation on an initial value and every element in the set, returning the final result.",
		signatures: &["set::fold(set, $initial: value, $operator: closure) -> value"],
	},
	BuiltinFn {
		name: "set::intersect",
		description: "The set::intersect function calculates the values which intersect two sets, returning a single set containing the values which are in both sets.",
		signatures: &["set::intersect(set, $other: set) -> set"],
	},
	BuiltinFn {
		name: "set::is_empty",
		description: "The set::is_empty function checks whether the set is empty or not.",
		signatures: &["set::is_empty(set) -> bool"],
	},
	BuiltinFn {
		name: "set::join",
		description: "The set::join function joins all values in a set together into a string, with a string separator in between each value.",
		signatures: &["set::join(set, $separator: string) -> string"],
	},
	BuiltinFn {
		name: "set::last",
		description: "The set::last function returns the last value from a set.",
		signatures: &["set::last(set) -> any"],
	},
	BuiltinFn {
		name: "set::len",
		description: "The set::len function calculates the length of a set, returning a number. This function counts unique items only.",
		signatures: &["set::len(set) -> number"],
	},
	BuiltinFn {
		name: "set::map",
		description: "The set::map function allows the user to call an anonymous function (closure) that is performed on every item in the set before passing it on.",
		signatures: &["set::map(set, $operator: closure) -> set"],
	},
	BuiltinFn {
		name: "set::max",
		description: "The set::max function returns the greatest value from a set of values.",
		signatures: &["set::max(set) -> any"],
	},
	BuiltinFn {
		name: "set::min",
		description: "The set::min function returns the least value from a set of values.",
		signatures: &["set::min(set) -> any"],
	},
	BuiltinFn {
		name: "set::reduce",
		description: "The set::reduce function applies an operation on every element in the set, returning the final result.",
		signatures: &["set::reduce(set, $operator: closure) -> value"],
	},
	BuiltinFn {
		name: "set::remove",
		description: "The set::remove function removes a value from a set.",
		signatures: &["set::remove(set, $remove: value) -> set"],
	},
	BuiltinFn {
		name: "set::slice",
		description: "The set::slice function returns a slice of a set by position.",
		signatures: &[
			"set::slice(set) -> set",
			"set::slice(set, $start: int) -> set",
			"set::slice(set, $start: int, $end: int) -> set",
			"set::slice(set, $range: range<int>) -> set",
		],
	},
	BuiltinFn {
		name: "set::union",
		description: "The set::union function combines two sets together, removing duplicate values, and returning a single set.",
		signatures: &["set::union(set, $other: set) -> set"],
	},
	BuiltinFn {
		name: "string::capitalize",
		description: "The string::capitalize function capitalizes the first letter of each word in a string.",
		signatures: &["string::capitalize(string) -> string"],
	},
	BuiltinFn {
		name: "string::concat",
		description: "The string::concat function concatenates values together into a single string.",
		signatures: &["string::concat(value, ...) -> string"],
	},
	BuiltinFn {
		name: "string::contains",
		description: "The string::contains function checks whether a string contains another string.",
		signatures: &["string::contains(string, $predicate: string) -> bool"],
	},
	BuiltinFn {
		name: "string::distance::damerau_levenshtein",
		description: "The string::distance::damerau_levenshtein function returns the Damerau-Levenshtein distance between two strings.",
		signatures: &["string::distance::damerau_levenshtein(string, string) -> int"],
	},
	BuiltinFn {
		name: "string::distance::hamming",
		description: "The string::distance::hamming function returns the Hamming distance between two strings of equal length.",
		signatures: &["string::distance::hamming(string, string) -> int"],
	},
	BuiltinFn {
		name: "string::distance::levenshtein",
		description: "The string::distance::levenshtein function returns the Levenshtein distance between two strings.",
		signatures: &["string::distance::levenshtein(string, string) -> int"],
	},
	BuiltinFn {
		name: "string::distance::normalized_damerau_levenshtein",
		description: "The string::distance::normalized_damerau_levenshtein function returns the normalized Damerau-Levenshtein distance between two strings. Normalized means that identical strings will return a score of...",
		signatures: &["string::distance::normalized_damerau_levenshtein(string, string) -> float"],
	},
	BuiltinFn {
		name: "string::distance::normalized_levenshtein",
		description: "The string::distance::normalized_levenshtein function returns the normalized Levenshtein distance between two strings. Normalized means that identical strings will return a score of 1, with less si...",
		signatures: &["string::distance::normalized_levenshtein(string, string) -> float"],
	},
	BuiltinFn {
		name: "string::distance::osa",
		description: "> [!NOTE] > This function was known as string::distance::osa_distance in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::distance::normalized_levenshtein(string, string) -> int"],
	},
	BuiltinFn {
		name: "string::ends_with",
		description: "> [!NOTE] > This function was known as string::endsWith in versions of SurrrealDB before 2.0. The behaviour has not changed.",
		signatures: &["string::ends_with(string, $other: string) -> bool"],
	},
	BuiltinFn {
		name: "string::html::encode",
		description: "The string::html::encode function encodes special characters into HTML entities to prevent HTML injection. It is recommended to use this function in most cases when retrieving any untrusted content...",
		signatures: &["string::html::encode(string) -> string"],
	},
	BuiltinFn {
		name: "string::html::sanitize",
		description: "The string::html::sanitize function sanitizes HTML code to prevent the most dangerous subset of HTML injection that can lead to attacks like cross-site scripting, layout breaking or clickjacking. T...",
		signatures: &["string::html::sanitize(string) -> string"],
	},
	BuiltinFn {
		name: "string::is_alpha",
		description: "> [!NOTE] > This function was known as string::is::alpha in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_alpha(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_alphanum",
		description: "> [!NOTE] > This function was known as string::is::alphanum in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_alphanum(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_ascii",
		description: "> [!NOTE] > This function was known as string::is::ascii in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_ascii(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_datetime",
		description: "> [!NOTE] > This function was known as string::is::datetime in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_datetime(string, $format: option<string>) -> bool"],
	},
	BuiltinFn {
		name: "string::is_domain",
		description: "> [!NOTE] > This function was known as string::is::domain in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_domain(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_email",
		description: "> [!NOTE] > This function was known as string::is::email in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_email(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_hexadecimal",
		description: "> [!NOTE] > This function was known as string::is::hexadecimal in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_hexadecimal(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_ip",
		description: "> [!NOTE] > This function was known as string::is::ip in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_ip(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_ipv4",
		description: "> [!NOTE] > This function was known as string::is::ipv4 in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_ipv4(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_ipv6",
		description: "> [!NOTE] > This function was known as string::is::ipv6 in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_ipv6(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_latitude",
		description: "> [!NOTE] > This function was known as string::is::latitude in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_latitude(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_longitude",
		description: "> [!NOTE] > This function was known as string::is::longitude in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_longitude(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_numeric",
		description: "> [!NOTE] > This function was known as string::is::numeric in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_numeric(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_record",
		description: "> [!NOTE] > This function was known as string::is::record in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_record(string, $table_name: option<string|table>) -> bool"],
	},
	BuiltinFn {
		name: "string::is_semver",
		description: "> [!NOTE] > This function was known as string::is::semver in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_semver(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_ulid",
		description: "> [!NOTE] > This function was known as string::is::ulid in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_ulid(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_url",
		description: "> [!NOTE] > This function was known as string::is::url in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_url(string) -> bool"],
	},
	BuiltinFn {
		name: "string::is_uuid",
		description: "> [!NOTE] > This function was known as string::is::uuid in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["string::is_uuid(string) -> bool"],
	},
	BuiltinFn {
		name: "string::join",
		description: "The string::join function joins strings or stringified values together with a delimiter.",
		signatures: &["string::join($delimiter: value, value...) -> string"],
	},
	BuiltinFn {
		name: "string::len",
		description: "The string::len function returns the length of a given string in characters.",
		signatures: &["string::len(string) -> number"],
	},
	BuiltinFn {
		name: "string::lowercase",
		description: "The string::lowercase function converts a string to lowercase.",
		signatures: &["string::lowercase(string) -> string"],
	},
	BuiltinFn {
		name: "string::matches",
		description: "The string::matches function performs a regex match on a string.",
		signatures: &["string::matches(string, $match_with: string|regex) -> bool"],
	},
	BuiltinFn {
		name: "string::repeat",
		description: "The string::repeat function repeats a string a number of times.",
		signatures: &["string::repeat(string, $times: number) -> string"],
	},
	BuiltinFn {
		name: "string::replace",
		description: "The string::replace function replaces an occurrence of a string with another string.",
		signatures: &[
			"string::replace(string, $from: string, $to: string) -> string",
			"string::replace(string, $from: string|regex, $to: string) -> string",
		],
	},
	BuiltinFn {
		name: "string::reverse",
		description: "The string::reverse  function reverses a string.",
		signatures: &["string::reverse(string) -> string"],
	},
	BuiltinFn {
		name: "string::semver::compare",
		description: "The string::semver::compare function performs a comparison on two semver strings and returns a number.",
		signatures: &["string::semver::compare(string, $other: string) -> 1|0|-1"],
	},
	BuiltinFn {
		name: "string::semver::inc::major",
		description: "The string::semver::inc::major function increments the major number of a semver string. As a result, the minor and patch numbers are reset to zero.",
		signatures: &["string::semver::inc::major(string) -> string"],
	},
	BuiltinFn {
		name: "string::semver::inc::minor",
		description: "The string::semver::inc::minor function increments the minor number of a semver string. As a result, the patch number is reset to zero.",
		signatures: &["string::semver::inc::minor(string) -> string"],
	},
	BuiltinFn {
		name: "string::semver::inc::patch",
		description: "The string::semver::inc::patch function increments the patch number of a semver string.",
		signatures: &["string::semver::inc::patch(string) -> string"],
	},
	BuiltinFn {
		name: "string::semver::major",
		description: "The string::semver::major function extracts the major number out of a semver string.",
		signatures: &["string::semver::major(string) -> number"],
	},
	BuiltinFn {
		name: "string::semver::minor",
		description: "The string::semver::minor function extracts the minor number out of a semver string.",
		signatures: &["string::semver::minor(string) -> number"],
	},
	BuiltinFn {
		name: "string::semver::patch",
		description: "The string::semver::patch function extracts the patch number out of a semver string.",
		signatures: &["string::semver::patch(string) -> number"],
	},
	BuiltinFn {
		name: "string::semver::set::major",
		description: "The string::semver::set::major function sets the major number of a semver string without changing the minor and patch numbers.",
		signatures: &["string::semver::set::major(string, $major: number) -> string"],
	},
	BuiltinFn {
		name: "string::semver::set::minor",
		description: "The string::semver::set::minor function sets the minor number of a semver string without changing the major and patch numbers.",
		signatures: &["string::semver::set::minor(string, $minor: number) -> string"],
	},
	BuiltinFn {
		name: "string::semver::set::patch",
		description: "The string::semver::set::patch function sets the patch number of a semver string without changing the major and minor numbers.",
		signatures: &["string::semver::set::patch(string, $patch: number) -> string"],
	},
	BuiltinFn {
		name: "string::similarity::fuzzy",
		description: "Built-in function string::similarity::fuzzy",
		signatures: &["string::similarity::fuzzy(string, string) -> int"],
	},
	BuiltinFn {
		name: "string::similarity::jaro",
		description: "The string::similarity::jaro function returns the Jaro similarity between two strings. Two strings that are identical have a score of 1, while less similar strings will have lower scores as the dis...",
		signatures: &["string::similarity::jaro(string, string) -> float"],
	},
	BuiltinFn {
		name: "string::similarity::jaro_winkler",
		description: "The string::similarity::jaro_winkler function returns the Jaro-Winkler similarity between two strings. Two strings that are identical have a score of 1, while less similar strings will have lower s...",
		signatures: &["string::similarity::jaro_winkler(string, string) -> float"],
	},
	BuiltinFn {
		name: "string::slice",
		description: "The string::slice function extracts and returns a section of a string.",
		signatures: &["string::slice(string, $from: number, $to: number) -> string"],
	},
	BuiltinFn {
		name: "string::slug",
		description: "The string::slug  function converts a string into a human and URL-friendly string.",
		signatures: &["string::slug(string) -> string"],
	},
	BuiltinFn {
		name: "string::split",
		description: "The string::split function splits a string by a given delimiter.",
		signatures: &["string::split(string, $delimiter: string) -> array"],
	},
	BuiltinFn {
		name: "string::starts_with",
		description: "> [!NOTE] > This function was known as string::startsWith in versions of SurrrealDB before 2.0. The behaviour has not changed.",
		signatures: &["string::starts_with(string, $predicate: string) -> bool"],
	},
	BuiltinFn {
		name: "string::trim",
		description: "The string::trim function removes whitespace from the start and end of a string.",
		signatures: &["string::trim(string) -> string"],
	},
	BuiltinFn {
		name: "string::uppercase",
		description: "The string::uppercase function converts a string to uppercase.",
		signatures: &["string::uppercase(string) -> string"],
	},
	BuiltinFn {
		name: "string::words",
		description: "The string::words function splits a string into an array of separate words.",
		signatures: &["string::words(string) -> array"],
	},
	BuiltinFn {
		name: "time::ceil",
		description: "The time::ceil function rounds a datetime up to the next largest duration.",
		signatures: &["time::ceil(datetime, $ceiling: duration) -> datetime"],
	},
	BuiltinFn {
		name: "time::day",
		description: "The time::day function extracts the day as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::day(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::epoch",
		description: "The time::epoch constant returns the datetime for the UNIX epoch (January 1, 1970).",
		signatures: &[],
	},
	BuiltinFn {
		name: "time::floor",
		description: "The time::floor function rounds a datetime down by a specific duration.",
		signatures: &["time::floor(datetime, $floor: duration) -> datetime"],
	},
	BuiltinFn {
		name: "time::format",
		description: "The time::format function outputs a datetime as a string according to a specific format.",
		signatures: &["time::format(datetime, $format: string) -> string"],
	},
	BuiltinFn {
		name: "time::from_micros",
		description: "The time::from_micros function calculates a datetime based on the microseconds since January 1, 1970 0:00:00 UTC.",
		signatures: &["time::from_micros(number) -> datetime"],
	},
	BuiltinFn {
		name: "time::from_millis",
		description: "The time::from_millis function calculates a datetime based on the milliseconds since January 1, 1970 0:00:00 UTC.",
		signatures: &["time::from_millis(number) -> datetime"],
	},
	BuiltinFn {
		name: "time::from_nanos",
		description: "The time::from_nanos function calculates a datetime based on the nanoseconds since January 1, 1970 0:00:00 UTC.",
		signatures: &["time::from_nanos(number) -> datetime"],
	},
	BuiltinFn {
		name: "time::from_secs",
		description: "The time::from_secs function calculates a datetime based on the seconds since January 1, 1970 0:00:00 UTC.",
		signatures: &["time::from_secs(number) -> datetime"],
	},
	BuiltinFn {
		name: "time::from_ulid",
		description: "The time::from_ulid function calculates a datetime based on the ULID.",
		signatures: &["time::from_ulid(ulid) -> datetime"],
	},
	BuiltinFn {
		name: "time::from_unix",
		description: "The time::from_unix function calculates a datetime based on the seconds since January 1, 1970 0:00:00 UTC.",
		signatures: &["time::from_unix(number) -> datetime"],
	},
	BuiltinFn {
		name: "time::from_uuid",
		description: "The time::from_uuid function calculates a datetime based on the UUID.",
		signatures: &["time::from_uuid(uuid) -> datetime"],
	},
	BuiltinFn {
		name: "time::group",
		description: "The time::group function reduces and rounds a datetime down to a particular time interval.",
		signatures: &[
			"time::group(datetime, $group_by: 'year'|'month'|'day'|'hour'|'minute'|'second') -> datetime",
		],
	},
	BuiltinFn {
		name: "time::hour",
		description: "The time::hour function extracts the hour as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::hour(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::max",
		description: "The time::max function returns the greatest datetime from an array of datetimes.",
		signatures: &["time::max(array<datetime>) -> datetime"],
	},
	BuiltinFn {
		name: "time::maximum",
		description: "The time::maximum constant returns the greatest possible datetime that can be used.",
		signatures: &["time::maximum -> datetime"],
	},
	BuiltinFn {
		name: "time::micros",
		description: "The time::micros function extracts the microseconds as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::micros(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::millis",
		description: "The time::millis function extracts the milliseconds as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::millis(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::min",
		description: "The time::min function returns the least datetime from an array of datetimes.",
		signatures: &["time::min(array<datetime>) -> datetime"],
	},
	BuiltinFn {
		name: "time::minimum",
		description: "The time::minimum constant returns the least possible datetime that can be used.",
		signatures: &["time::minimum -> datetime"],
	},
	BuiltinFn {
		name: "time::minute",
		description: "The time::minute function extracts the minutes as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::minute(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::month",
		description: "The time::month function extracts the month as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::month(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::nano",
		description: "The time::nanofunction returns a datetime as an integer representing the number of nanoseconds since the UNIX epoch until a datetime, or the current date if no datetime argument is present.",
		signatures: &["time::nano(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::now",
		description: "The time::now function returns the current datetime as an ISO8601 timestamp.",
		signatures: &["time::now() -> datetime"],
	},
	BuiltinFn {
		name: "time::round",
		description: "The time::round function rounds a datetime up by a specific duration.",
		signatures: &["time::round(datetime, $round_to: duration) -> datetime"],
	},
	BuiltinFn {
		name: "time::second",
		description: "The time::second function extracts the second as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::second(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::set_day",
		description: "The time::set_day function sets the day value of a datetime.",
		signatures: &["time::set_day(datetime, $day: integer) -> datetime"],
	},
	BuiltinFn {
		name: "time::set_hour",
		description: "The time::set_hour function sets the hour value of a datetime.",
		signatures: &["time::set_hour(datetime, $hour: integer) -> datetime"],
	},
	BuiltinFn {
		name: "time::set_minute",
		description: "The time::set_minute function sets the minute value of a datetime.",
		signatures: &["time::set_minute(datetime, $minute: integer) -> datetime"],
	},
	BuiltinFn {
		name: "time::set_month",
		description: "The time::set_month function sets the month value of a datetime.",
		signatures: &["time::set_month(datetime, $month: integer) -> datetime"],
	},
	BuiltinFn {
		name: "time::set_nanosecond",
		description: "The time::set_nanosecond function sets the nanosecond value of a datetime.",
		signatures: &["time::set_nanosecond(datetime, $nanosecond: integer) -> datetime"],
	},
	BuiltinFn {
		name: "time::set_second",
		description: "The time::set_second function sets the second value of a datetime.",
		signatures: &["time::set_second(datetime, $second: integer) -> datetime"],
	},
	BuiltinFn {
		name: "time::set_year",
		description: "The time::set_year function sets the year value of a datetime.",
		signatures: &["time::set_year(datetime, $year: integer) -> datetime"],
	},
	BuiltinFn {
		name: "time::timezone",
		description: "The time::timezone function returns the current local timezone offset in hours.",
		signatures: &["time::timezone() -> string"],
	},
	BuiltinFn {
		name: "time::unix",
		description: "The time::unix function returns a datetime as an integer representing the number of seconds since the UNIX epoch until a certain datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::unix(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::wday",
		description: "The time::wday function extracts the week day as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::wday(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::week",
		description: "The time::week function extracts the week as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::week(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::yday",
		description: "The time::yday function extracts the day of the year as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::yday(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "time::year",
		description: "The time::year function extracts the year as a number from a datetime, or from the current date if no datetime argument is present.",
		signatures: &["time::year(option<datetime>) -> number"],
	},
	BuiltinFn {
		name: "type::array",
		description: "The type::array function converts a value into an array.",
		signatures: &["type::array(array|range) -> array"],
	},
	BuiltinFn {
		name: "type::bool",
		description: "The type::bool function converts a value into a boolean.",
		signatures: &["type::bool(bool|string) -> bool"],
	},
	BuiltinFn {
		name: "type::bytes",
		description: "The type::bytes function converts a value into bytes.",
		signatures: &["type::bytes(bytes|string) -> bool"],
	},
	BuiltinFn {
		name: "type::datetime",
		description: "The type::datetime function converts a value into a datetime.",
		signatures: &["type::datetime(datetime|string) -> datetime"],
	},
	BuiltinFn {
		name: "type::decimal",
		description: "The type::decimal function converts a value into a decimal.",
		signatures: &["type::decimal(decimal|float|int|number|string) -> decimal"],
	},
	BuiltinFn {
		name: "type::duration",
		description: "The type::duration function converts a value into a duration.",
		signatures: &["type::duration(duration|string) -> duration"],
	},
	BuiltinFn {
		name: "type::field",
		description: "The type::field function projects a single field within a SELECT statement.",
		signatures: &["type::field(string)"],
	},
	BuiltinFn {
		name: "type::fields",
		description: "The type::fields function projects one or more fields within a SELECT statement.",
		signatures: &["type::fields(array<string>)"],
	},
	BuiltinFn {
		name: "type::file",
		description: "The type::file function converts two strings representing a bucket name and a key into a file pointer.",
		signatures: &["type::file($bucket: string, $key: string) -> file"],
	},
	BuiltinFn {
		name: "type::float",
		description: "The type::float function converts a value into a float.",
		signatures: &["type::float(decimal|float|int|number|string) -> float"],
	},
	BuiltinFn {
		name: "type::int",
		description: "The type::int function converts a value into an integer.",
		signatures: &["type::int(decimal|float|int|number|string) -> int"],
	},
	BuiltinFn {
		name: "type::is_array",
		description: "> [!NOTE] > This function was known as type::is::array in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_array(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_bool",
		description: "> [!NOTE] > This function was known as type::is::bool in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_bool(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_bytes",
		description: "> [!NOTE] > This function was known as type::is::bytes in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_bytes(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_collection",
		description: "> [!NOTE] > This function was known as type::is::collection in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_collection(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_datetime",
		description: "> [!NOTE] > This function was known as type::is::datetime in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_datetime(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_decimal",
		description: "> [!NOTE] > This function was known as type::is::decimal in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_decimal(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_duration",
		description: "> [!NOTE] > This function was known as type::is::duration in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_duration(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_float",
		description: "> [!NOTE] > This function was known as type::is::float in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_float(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_geometry",
		description: "> [!NOTE] > This function was known as type::is::geometry in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_geometry(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_int",
		description: "> [!NOTE] > This function was known as type::is::int in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_int(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_line",
		description: "> [!NOTE] > This function was known as type::is::line in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_line(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_multiline",
		description: "> [!NOTE] > This function was known as type::is::multiline in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_multiline(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_multipoint",
		description: "> [!NOTE] > This function was known as type::is::multipoint in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_multipoint(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_multipolygon",
		description: "> [!NOTE] > This function was known as type::is::multipolygon in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_multipolygon(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_none",
		description: "> [!NOTE] > This function was known as type::is::none in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_none(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_null",
		description: "> [!NOTE] > This function was known as type::is::null in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_null(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_number",
		description: "> [!NOTE] > This function was known as type::is::number in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_number(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_object",
		description: "> [!NOTE] > This function was known as type::is::object in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_object(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_point",
		description: "> [!NOTE] > This function was known as type::is::point in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_point(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_polygon",
		description: "> [!NOTE] > This function was known as type::is::polygon in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_polygon(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_range",
		description: "> [!NOTE] > This function was known as type::is::range in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_range(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_record",
		description: "> [!NOTE] > This function was known as type::is::record in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_record(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_string",
		description: "> [!NOTE] > This function was known as type::is::string in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_string(any) -> bool"],
	},
	BuiltinFn {
		name: "type::is_uuid",
		description: "> [!NOTE] > This function was known as type::is::uuid in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &["type::is_uuid(any) -> bool"],
	},
	BuiltinFn {
		name: "type::number",
		description: "The type::number function converts a value into a number.",
		signatures: &["type::number(decimal|float|int|number|string) -> number"],
	},
	BuiltinFn {
		name: "type::point",
		description: "The type::point function converts a value into a geometry point.",
		signatures: &["type::point(array|point) -> point"],
	},
	BuiltinFn {
		name: "type::range",
		description: "The type::range function converts a value into a range. It accepts a single argument, either a range or an array with two values. If the argument is an array, it will be converted into a range, sim...",
		signatures: &["type::range(range|array) -> range<record>"],
	},
	BuiltinFn {
		name: "type::record",
		description: "> [!NOTE] > This function was known as type::thing in versions of SurrrealDB before 3.0.0-beta. The behaviour has not changed.",
		signatures: &[
			"type::record($table: any, $key: any) -> record",
			"type::record($record: record|string, $table_name: option<string>) -> record",
		],
	},
	BuiltinFn {
		name: "type::string",
		description: "The type::string function converts any value except NONE, NULL, and bytes into a string.",
		signatures: &["type::string(any) -> string"],
	},
	BuiltinFn {
		name: "type::string_lossy",
		description: "The type::string_lossy function converts any value except NONE, NULL, and bytes into a string. In the case of bytes, it will not return an error if the bytes are not valid UTF-8. Instead, invalid b...",
		signatures: &["type::string(any) -> string"],
	},
	BuiltinFn {
		name: "type::table",
		description: "The type::table function converts a value into a table name.",
		signatures: &["type::table(record|string) -> string"],
	},
	BuiltinFn {
		name: "type::uuid",
		description: "The type::uuid function converts a value into a UUID.",
		signatures: &["type::uuid(string|uuid) -> uuid"],
	},
	BuiltinFn {
		name: "value::diff",
		description: "The value::diff function returns an object that shows the JSON Patch operation(s) required for the first value to equal the second one.",
		signatures: &["value::diff(value, $other: value) -> array<object>"],
	},
	BuiltinFn {
		name: "value::patch",
		description: "The value::patch function applies an array of JSON Patch operations to a value.",
		signatures: &["value::patch(value, $patch: array<object>) -> value"],
	},
	BuiltinFn {
		name: "vector::add",
		description: "The vector::add function performs element-wise addition of two vectors, where each element in the first vector is added to the corresponding element in the second vector.",
		signatures: &["vector::add(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "vector::angle",
		description: "The vector::angle function computes the angle between two vectors, providing a measure of the orientation difference between them.",
		signatures: &["vector::angle(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::cross",
		description: "The vector::cross function computes the cross product of two vectors, which results in a vector that is orthogonal (perpendicular) to the plane containing the original vectors.",
		signatures: &["vector::cross(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "vector::distance::chebyshev",
		description: "The vector::distance::chebyshev function computes the Chebyshev distance (also known as maximum value distance) between two vectors, which is the greatest of their differences along any coordinate ...",
		signatures: &["vector::distance::chebyshev(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::distance::euclidean",
		description: "The vector::distance::euclidean function computes the Euclidean distance between two vectors, providing a measure of the straight-line distance between two points in a multi-dimensional space.",
		signatures: &["vector::distance::euclidean(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::distance::hamming",
		description: "The vector::distance::hamming function computes the Hamming distance between two vectors, measuring the minimum number of substitutions required to change one vector into the other, useful for comp...",
		signatures: &["vector::distance::hamming(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::distance::knn",
		description: "The vector::distance::knn function returns the distance computed during the query by the Knn operator (avoiding recomputation).",
		signatures: &["vector::distance::knn() -> number"],
	},
	BuiltinFn {
		name: "vector::distance::manhattan",
		description: "The vector::distance::manhattan  function computes the Manhattan distance (also known as the L1 norm or Taxicab geometry) between two vectors, which is the sum of the absolute differences of their ...",
		signatures: &["vector::distance::manhattan(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::distance::minkowski",
		description: "The vector::distance::minkowski function computes the Minkowski distance between two vectors, a generalization of other distance metrics such as Euclidean and Manhattan when parameterized with diff...",
		signatures: &[
			"vector::distance::minkowski(array, $other: array, $p_value: number) -> number",
		],
	},
	BuiltinFn {
		name: "vector::divide",
		description: "The vector::divide function performs element-wise division between two vectors, where each element in the first vector is divided by the corresponding element in the second vector.",
		signatures: &["vector::divide(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "vector::dot",
		description: "The vector::dot function computes the dot product of two vectors, which is the sum of the products of the corresponding entries of the two sequences of numbers.",
		signatures: &["vector::dot(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::magnitude",
		description: "The vector::magnitude function computes the magnitude (or length) of a vector, providing a measure of the size of the vector in multi-dimensional space.",
		signatures: &["vector::magnitude(array) -> number"],
	},
	BuiltinFn {
		name: "vector::multiply",
		description: "The vector::multiply function performs element-wise multiplication of two vectors, where each element in the first vector is multiplied by the corresponding element in the second vector.",
		signatures: &["vector::multiply(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::normalize",
		description: "The vector::normalize function computes the normalization of a vector, transforming it to a unit vector (a vector of length 1) that maintains the original direction.",
		signatures: &["vector::normalize(array) -> array"],
	},
	BuiltinFn {
		name: "vector::project",
		description: "The vector::project function computes the projection of one vector onto another, providing a measure of the shadow of one vector on the other. The projection is obtained by multiplying the magnitud...",
		signatures: &["vector::project(array, $other: array) -> array"],
	},
	BuiltinFn {
		name: "vector::scale",
		description: "The vector::scale function multiplies each item in a vector by a number.",
		signatures: &["vector::scale(array, $other: number) -> array"],
	},
	BuiltinFn {
		name: "vector::similarity::cosine",
		description: "The vector::similarity::cosine function computes the Cosine similarity between two vectors, indicating the cosine of the angle between them, which is a measure of how closely two vectors are orient...",
		signatures: &["vector::similarity::cosine(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::similarity::jaccard",
		description: "The vector::similarity::jaccard function computes the Jaccard similarity between two vectors, measuring the intersection divided by the union of the datasets represented by the vectors.",
		signatures: &["vector::similarity::jaccard(array, $other: array) -> number"],
	},
	BuiltinFn {
		name: "vector::similarity::pearson",
		description: "The vector::similarity::pearson function Computes the Pearson correlation coefficient between two vectors, reflecting the degree of linear relationship between them.",
		signatures: &["vector::similarity::pearson(array, array) -> number"],
	},
	BuiltinFn {
		name: "vector::subtract",
		description: "The vector::subtract function performs element-wise subtraction between two vectors, where each element in the second vector is subtracted from the corresponding element in the first vector.",
		signatures: &["vector::subtract(array, $other: array) -> array"],
	},
];
