use crate::upstream::syn::token::Keyword;

fn keyword_str(k: Keyword) -> &'static str {
	match k {
		Keyword::Access => k.as_str(),
		Keyword::After => k.as_str(),
		Keyword::Algorithm => k.as_str(),
		Keyword::All => k.as_str(),
		Keyword::Alter => k.as_str(),
		Keyword::Always => k.as_str(),
		Keyword::Analyzer => k.as_str(),
		Keyword::Api => k.as_str(),
		Keyword::As => k.as_str(),
		Keyword::Ascending => k.as_str(),
		Keyword::Ascii => k.as_str(),
		Keyword::Assert => k.as_str(),
		Keyword::Async => k.as_str(),
		Keyword::At => k.as_str(),
		Keyword::Authenticate => k.as_str(),
		Keyword::Auto => k.as_str(),
		Keyword::Backend => k.as_str(),
		Keyword::Batch => k.as_str(),
		Keyword::Bearer => k.as_str(),
		Keyword::Before => k.as_str(),
		Keyword::Begin => k.as_str(),
		Keyword::Blank => k.as_str(),
		Keyword::Bucket => k.as_str(),
		Keyword::Reject => k.as_str(),
		Keyword::Bm25 => k.as_str(),
		Keyword::Break => k.as_str(),
		Keyword::By => k.as_str(),
		Keyword::Camel => k.as_str(),
		Keyword::Cancel => k.as_str(),
		Keyword::Cascade => k.as_str(),
		Keyword::ChangeFeed => k.as_str(),
		Keyword::Changes => k.as_str(),
		Keyword::Capacity => k.as_str(),
		Keyword::Class => k.as_str(),
		Keyword::Comment => k.as_str(),
		Keyword::Commit => k.as_str(),
		Keyword::Compact => k.as_str(),
		Keyword::Concurrently => k.as_str(),
		Keyword::Config => k.as_str(),
		Keyword::Content => k.as_str(),
		Keyword::Continue => k.as_str(),
		Keyword::Computed => k.as_str(),
		Keyword::Count => k.as_str(),
		Keyword::Create => k.as_str(),
		Keyword::Database => k.as_str(),
		Keyword::Default => k.as_str(),
		Keyword::Define => k.as_str(),
		Keyword::Delete => k.as_str(),
		Keyword::Descending => k.as_str(),
		Keyword::Diff => k.as_str(),
		Keyword::Dimension => k.as_str(),
		Keyword::Distance => k.as_str(),
		Keyword::Drop => k.as_str(),
		Keyword::Duplicate => k.as_str(),
		Keyword::Efc => k.as_str(),
		Keyword::Edgengram => k.as_str(),
		Keyword::Event => k.as_str(),
		Keyword::Else => k.as_str(),
		Keyword::End => k.as_str(),
		Keyword::Enforced => k.as_str(),
		Keyword::Exclude => k.as_str(),
		Keyword::Exists => k.as_str(),
		Keyword::Expired => k.as_str(),
		Keyword::Explain => k.as_str(),
		Keyword::Expunge => k.as_str(),
		Keyword::ExtendCandidates => k.as_str(),
		Keyword::False => k.as_str(),
		Keyword::Fetch => k.as_str(),
		Keyword::Field => k.as_str(),
		Keyword::Fields => k.as_str(),
		Keyword::Filters => k.as_str(),
		Keyword::Flexible => k.as_str(),
		Keyword::For => k.as_str(),
		Keyword::From => k.as_str(),
		Keyword::Full => k.as_str(),
		Keyword::Fulltext => k.as_str(),
		Keyword::Function => k.as_str(),
		Keyword::Functions => k.as_str(),
		Keyword::Grant => k.as_str(),
		Keyword::Graphql => k.as_str(),
		Keyword::Group => k.as_str(),
		Keyword::Headers => k.as_str(),
		Keyword::Highlights => k.as_str(),
		Keyword::Hnsw => k.as_str(),
		Keyword::Ignore => k.as_str(),
		Keyword::Include => k.as_str(),
		Keyword::Index => k.as_str(),
		Keyword::Info => k.as_str(),
		Keyword::Insert => k.as_str(),
		Keyword::Into => k.as_str(),
		Keyword::If => k.as_str(),
		Keyword::Is => k.as_str(),
		Keyword::Issuer => k.as_str(),
		Keyword::Jwt => k.as_str(),
		Keyword::Jwks => k.as_str(),
		Keyword::HashedVector => k.as_str(),
		Keyword::Key => k.as_str(),
		Keyword::KeepPrunedConnections => k.as_str(),
		Keyword::Kill => k.as_str(),
		Keyword::Let => k.as_str(),
		Keyword::Limit => k.as_str(),
		Keyword::Live => k.as_str(),
		Keyword::Lowercase => k.as_str(),
		Keyword::Lm => k.as_str(),
		Keyword::M => k.as_str(),
		Keyword::M0 => k.as_str(),
		Keyword::Mapper => k.as_str(),
		Keyword::MaxDepth => k.as_str(),
		Keyword::Middleware => k.as_str(),
		Keyword::Merge => k.as_str(),
		Keyword::Model => k.as_str(),
		Keyword::Module => k.as_str(),
		Keyword::Namespace => k.as_str(),
		Keyword::Ngram => k.as_str(),
		Keyword::No => k.as_str(),
		Keyword::NoIndex => k.as_str(),
		Keyword::None => k.as_str(),
		Keyword::Null => k.as_str(),
		Keyword::Numeric => k.as_str(),
		Keyword::Omit => k.as_str(),
		Keyword::On => k.as_str(),
		Keyword::Only => k.as_str(),
		Keyword::Option => k.as_str(),
		Keyword::Order => k.as_str(),
		Keyword::Original => k.as_str(),
		Keyword::Overwrite => k.as_str(),
		Keyword::Parallel => k.as_str(),
		Keyword::Param => k.as_str(),
		Keyword::Passhash => k.as_str(),
		Keyword::Password => k.as_str(),
		Keyword::Patch => k.as_str(),
		Keyword::Permissions => k.as_str(),
		Keyword::PostingsCache => k.as_str(),
		Keyword::PostingsOrder => k.as_str(),
		Keyword::Prepare => k.as_str(),
		Keyword::Punct => k.as_str(),
		Keyword::Purge => k.as_str(),
		Keyword::Range => k.as_str(),
		Keyword::Readonly => k.as_str(),
		Keyword::Rebuild => k.as_str(),
		Keyword::Reference => k.as_str(),
		Keyword::Refresh => k.as_str(),
		Keyword::Regex => k.as_str(),
		Keyword::Relate => k.as_str(),
		Keyword::Relation => k.as_str(),
		Keyword::Remove => k.as_str(),
		Keyword::Replace => k.as_str(),
		Keyword::Retry => k.as_str(),
		Keyword::Return => k.as_str(),
		Keyword::Revoke => k.as_str(),
		Keyword::Revoked => k.as_str(),
		Keyword::Roles => k.as_str(),
		Keyword::Root => k.as_str(),
		Keyword::Schemafull => k.as_str(),
		Keyword::Schemaless => k.as_str(),
		Keyword::Scope => k.as_str(),
		Keyword::Select => k.as_str(),
		Keyword::Sequence => k.as_str(),
		Keyword::Session => k.as_str(),
		Keyword::Set => k.as_str(),
		Keyword::Show => k.as_str(),
		Keyword::Signin => k.as_str(),
		Keyword::Signup => k.as_str(),
		Keyword::Since => k.as_str(),
		Keyword::Sleep => k.as_str(),
		Keyword::Snowball => k.as_str(),
		Keyword::Split => k.as_str(),
		Keyword::Start => k.as_str(),
		Keyword::Strict => k.as_str(),
		Keyword::Structure => k.as_str(),
		Keyword::System => k.as_str(),
		Keyword::Table => k.as_str(),
		Keyword::Tables => k.as_str(),
		Keyword::TempFiles => k.as_str(),
		Keyword::TermsCache => k.as_str(),
		Keyword::TermsOrder => k.as_str(),
		Keyword::Then => k.as_str(),
		Keyword::Throw => k.as_str(),
		Keyword::Timeout => k.as_str(),
		Keyword::Tokenizers => k.as_str(),
		Keyword::Token => k.as_str(),
		Keyword::To => k.as_str(),
		Keyword::Transaction => k.as_str(),
		Keyword::True => k.as_str(),
		Keyword::Type => k.as_str(),
		Keyword::Unique => k.as_str(),
		Keyword::Unset => k.as_str(),
		Keyword::Update => k.as_str(),
		Keyword::Upsert => k.as_str(),
		Keyword::Uppercase => k.as_str(),
		Keyword::Url => k.as_str(),
		Keyword::Use => k.as_str(),
		Keyword::User => k.as_str(),
		Keyword::Value => k.as_str(),
		Keyword::Values => k.as_str(),
		Keyword::Version => k.as_str(),
		Keyword::Vs => k.as_str(),
		Keyword::When => k.as_str(),
		Keyword::Where => k.as_str(),
		Keyword::With => k.as_str(),
		Keyword::AllInside => k.as_str(),
		Keyword::AndKw => k.as_str(),
		Keyword::AnyInside => k.as_str(),
		Keyword::Inside => k.as_str(),
		Keyword::Intersects => k.as_str(),
		Keyword::NoneInside => k.as_str(),
		Keyword::NotInside => k.as_str(),
		Keyword::OrKw => k.as_str(),
		Keyword::Outside => k.as_str(),
		Keyword::Not => k.as_str(),
		Keyword::And => k.as_str(),
		Keyword::Collate => k.as_str(),
		Keyword::ContainsAll => k.as_str(),
		Keyword::ContainsAny => k.as_str(),
		Keyword::ContainsNone => k.as_str(),
		Keyword::ContainsNot => k.as_str(),
		Keyword::Contains => k.as_str(),
		Keyword::In => k.as_str(),
		Keyword::Out => k.as_str(),
		Keyword::Normal => k.as_str(),
		Keyword::Any => k.as_str(),
		Keyword::Array => k.as_str(),
		Keyword::Geometry => k.as_str(),
		Keyword::Record => k.as_str(),
		Keyword::Bool => k.as_str(),
		Keyword::Bytes => k.as_str(),
		Keyword::Datetime => k.as_str(),
		Keyword::Decimal => k.as_str(),
		Keyword::Duration => k.as_str(),
		Keyword::Float => k.as_str(),
		Keyword::Fn => k.as_str(),
		Keyword::Silo => k.as_str(),
		Keyword::Mod => k.as_str(),
		Keyword::Int => k.as_str(),
		Keyword::Number => k.as_str(),
		Keyword::Object => k.as_str(),
		Keyword::String => k.as_str(),
		Keyword::Uuid => k.as_str(),
		Keyword::Ulid => k.as_str(),
		Keyword::Rand => k.as_str(),
		Keyword::References => k.as_str(),
		Keyword::Feature => k.as_str(),
		Keyword::Line => k.as_str(),
		Keyword::Point => k.as_str(),
		Keyword::Polygon => k.as_str(),
		Keyword::MultiPoint => k.as_str(),
		Keyword::MultiLine => k.as_str(),
		Keyword::MultiPolygon => k.as_str(),
		Keyword::Collection => k.as_str(),
		Keyword::File => k.as_str(),
		Keyword::FN => k.as_str(),
		Keyword::ML => k.as_str(),
		Keyword::Get => k.as_str(),
		Keyword::Post => k.as_str(),
		Keyword::Put => k.as_str(),
		Keyword::Trace => k.as_str(),
	}
}

/// All SurrealQL keywords recognized by the parser.
///
/// Built from the parser's `Keyword` enum via an exhaustive match.
/// Adding a variant to `Keyword` without adding it here causes a
/// compile error (missing match arm).
pub fn all_keywords() -> &'static [&'static str] {
	use std::sync::LazyLock;

	static KEYWORDS: LazyLock<Vec<&'static str>> = LazyLock::new(|| {
		use Keyword::*;
		let variants = [
			Access,
			After,
			Algorithm,
			All,
			Alter,
			Always,
			Analyzer,
			Api,
			As,
			Ascending,
			Ascii,
			Assert,
			Async,
			At,
			Authenticate,
			Auto,
			Backend,
			Batch,
			Bearer,
			Before,
			Begin,
			Blank,
			Bucket,
			Reject,
			Bm25,
			Break,
			By,
			Camel,
			Cancel,
			Cascade,
			ChangeFeed,
			Changes,
			Capacity,
			Class,
			Comment,
			Commit,
			Compact,
			Concurrently,
			Config,
			Content,
			Continue,
			Computed,
			Count,
			Create,
			Database,
			Default,
			Define,
			Delete,
			Descending,
			Diff,
			Dimension,
			Distance,
			Drop,
			Duplicate,
			Efc,
			Edgengram,
			Event,
			Else,
			End,
			Enforced,
			Exclude,
			Exists,
			Expired,
			Explain,
			Expunge,
			ExtendCandidates,
			False,
			Fetch,
			Field,
			Fields,
			Filters,
			Flexible,
			For,
			From,
			Full,
			Fulltext,
			Function,
			Functions,
			Grant,
			Graphql,
			Group,
			Headers,
			Highlights,
			Hnsw,
			Ignore,
			Include,
			Index,
			Info,
			Insert,
			Into,
			If,
			Is,
			Issuer,
			Jwt,
			Jwks,
			HashedVector,
			Key,
			KeepPrunedConnections,
			Kill,
			Let,
			Limit,
			Live,
			Lowercase,
			Lm,
			M,
			M0,
			Mapper,
			MaxDepth,
			Middleware,
			Merge,
			Model,
			Module,
			Namespace,
			Ngram,
			No,
			NoIndex,
			None,
			Null,
			Numeric,
			Omit,
			On,
			Only,
			Option,
			Order,
			Original,
			Overwrite,
			Parallel,
			Param,
			Passhash,
			Password,
			Patch,
			Permissions,
			PostingsCache,
			PostingsOrder,
			Prepare,
			Punct,
			Purge,
			Range,
			Readonly,
			Rebuild,
			Reference,
			Refresh,
			Regex,
			Relate,
			Relation,
			Remove,
			Replace,
			Retry,
			Return,
			Revoke,
			Revoked,
			Roles,
			Root,
			Schemafull,
			Schemaless,
			Scope,
			Select,
			Sequence,
			Session,
			Set,
			Show,
			Signin,
			Signup,
			Since,
			Sleep,
			Snowball,
			Split,
			Start,
			Strict,
			Structure,
			System,
			Table,
			Tables,
			TempFiles,
			TermsCache,
			TermsOrder,
			Then,
			Throw,
			Timeout,
			Tokenizers,
			Token,
			To,
			Transaction,
			True,
			Type,
			Unique,
			Unset,
			Update,
			Upsert,
			Uppercase,
			Url,
			Use,
			User,
			Value,
			Values,
			Version,
			Vs,
			When,
			Where,
			With,
			AllInside,
			AndKw,
			AnyInside,
			Inside,
			Intersects,
			NoneInside,
			NotInside,
			OrKw,
			Outside,
			Not,
			And,
			Collate,
			ContainsAll,
			ContainsAny,
			ContainsNone,
			ContainsNot,
			Contains,
			In,
			Out,
			Normal,
			Any,
			Array,
			Geometry,
			Record,
			Bool,
			Bytes,
			Datetime,
			Decimal,
			Duration,
			Float,
			Fn,
			Silo,
			Mod,
			Int,
			Number,
			Object,
			String,
			Uuid,
			Ulid,
			Rand,
			References,
			Feature,
			Line,
			Point,
			Polygon,
			MultiPoint,
			MultiLine,
			MultiPolygon,
			Collection,
			File,
			FN,
			ML,
			Get,
			Post,
			Put,
			Trace,
		];
		let mut kws: Vec<&str> = variants.iter().map(|k| keyword_str(*k)).collect();
		kws.sort();
		kws.dedup();
		kws
	});
	&KEYWORDS
}
